import Link from "next/link";
import { ActivityTimeline } from "@/components/shared/activity-timeline";
import { StatusBadge } from "@/components/shared/status-badge";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getPortalInvoice, getPortalProject } from "@/lib/api";
import { buildInvoiceTimeline, formatDate, formatDateTime, formatInvoiceCurrency, getInvoiceDisplayStatus } from "@/lib/document-workflow";

export default async function CustomerPortalInvoicePage({ params }: { params: Promise<{ invoiceId: string }> }) {
  const { invoiceId } = await params;
  const invoice = await getPortalInvoice(invoiceId);
  const project = await getPortalProject(invoice.projectId);
  return <main className="mx-auto flex min-h-screen w-full max-w-5xl flex-col gap-6 px-6 py-10"><div className="space-y-3"><Link href={`/customer-portal/projects/${project.id}`} className="text-sm text-muted-foreground underline">← Back to project</Link><h1 className="text-3xl font-semibold tracking-tight">Invoice #{invoice.invoiceNumber}</h1><StatusBadge status={getInvoiceDisplayStatus(invoice)} /></div><div className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]"><Card><CardHeader><CardTitle>Invoice summary</CardTitle></CardHeader><CardContent className="grid gap-4 text-sm sm:grid-cols-2"><div><div className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Project</div><div className="mt-1 font-medium">{project.name}</div></div><div><div className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Due date</div><div className="mt-1 font-medium">{formatDate(invoice.dueDate)}</div></div><div><div className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Subtotal</div><div className="mt-1 font-medium">{formatInvoiceCurrency(invoice.subtotal)}</div></div>{invoice.taxAmount > 0 && <div><div className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Tax</div><div className="mt-1 font-medium">{formatInvoiceCurrency(invoice.taxAmount)}</div></div>}<div><div className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Paid to date</div><div className="mt-1 font-medium">{formatInvoiceCurrency(invoice.paidAmount)}</div></div><div><div className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Balance due</div><div className="mt-1 font-medium">{formatInvoiceCurrency(invoice.balanceDue)}</div></div></CardContent></Card><ActivityTimeline title="Invoice timeline" items={buildInvoiceTimeline(invoice)} /></div><Card><CardHeader><CardTitle>Payment history</CardTitle></CardHeader><CardContent>{invoice.payments.length ? invoice.payments.map((payment) => <div key={payment.id} className="flex justify-between border-b border-border/60 py-3 text-sm last:border-0"><div><div className="font-medium">{formatInvoiceCurrency(payment.amount)}</div><div className="text-muted-foreground">{payment.method} · {formatDateTime(payment.paymentDate)}</div></div><span className="text-muted-foreground">Recorded</span></div>) : <p className="text-sm text-muted-foreground">No recorded payments yet.</p>}</CardContent></Card><a href={`/api/customer-portal/invoices/${invoice.id}/pdf`} target="_blank" rel="noreferrer" className={buttonVariants({ variant: "outline" })}>Download invoice PDF</a></main>;
}
