"use client";

import { useMemo, useState } from "react";
import { buildCompositeImportBatches, type ImportRow } from "./import-batches";

interface ImportFileShape {
  rows: ImportRow[];
  rowCount?: number;
  rejectedCount?: number;
  rejections?: unknown[];
}

export function CompositeImportClient() {
  const [fileName, setFileName] = useState<string | null>(null);
  const [rows, setRows] = useState<ImportRow[]>([]);
  const [rejectedCount, setRejectedCount] = useState<number | null>(null);
  const [completed, setCompleted] = useState(0);
  const [upserted, setUpserted] = useState(0);
  const [status, setStatus] = useState<"idle" | "ready" | "running" | "done" | "error">("idle");
  const [message, setMessage] = useState("Choose the normalized INDOT JSON generated by the governed importer.");

  const batches = useMemo(() => buildCompositeImportBatches(rows), [rows]);
  const batchCount = batches.length;

  async function onFileChange(file: File | undefined) {
    setCompleted(0);
    setUpserted(0);
    setRejectedCount(null);
    setRows([]);
    setFileName(file?.name ?? null);

    if (!file) {
      setStatus("idle");
      setMessage("Choose the normalized INDOT JSON generated by the governed importer.");
      return;
    }

    try {
      const parsed = JSON.parse(await file.text()) as ImportFileShape;
      if (!parsed || !Array.isArray(parsed.rows) || parsed.rows.length === 0) {
        throw new Error("The selected file does not contain an importable rows array.");
      }
      const parsedBatches = buildCompositeImportBatches(parsed.rows);
      setRows(parsed.rows);
      setRejectedCount(typeof parsed.rejectedCount === "number" ? parsed.rejectedCount : null);
      setStatus("ready");
      setMessage(`Validated file locally: ${parsed.rows.length.toLocaleString()} rows ready in ${parsedBatches.length.toLocaleString()} batches.`);
    } catch (error) {
      setStatus("error");
      setMessage(error instanceof Error ? error.message : "Unable to read the selected JSON file.");
    }
  }

  async function runImport() {
    if (!rows.length || status === "running") return;

    setStatus("running");
    setCompleted(0);
    setUpserted(0);
    setMessage("Starting authenticated production import…");

    let receivedTotal = 0;
    let upsertedTotal = 0;

    try {
      for (const batch of batches) {
        const response = await fetch("/api/costbook/composite-import", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ rows: batch }),
        });
        const body = (await response.json()) as { received?: number; upserted?: number; error?: string };
        if (!response.ok) {
          throw new Error(body.error || `Import failed with HTTP ${response.status}`);
        }

        receivedTotal += Number(body.received ?? batch.length);
        upsertedTotal += Number(body.upserted ?? 0);
        setCompleted(receivedTotal);
        setUpserted(upsertedTotal);
        setMessage(`Imported ${receivedTotal.toLocaleString()} of ${rows.length.toLocaleString()} rows…`);
      }

      setStatus("done");
      setMessage(`Production import complete: ${receivedTotal.toLocaleString()} rows received, ${upsertedTotal.toLocaleString()} rows upserted.`);
    } catch (error) {
      setStatus("error");
      setMessage(error instanceof Error ? error.message : "Production import failed.");
    }
  }

  const progress = rows.length ? Math.round((completed / rows.length) * 100) : 0;

  return (
    <div className="grid gap-4">
      <div className="rounded-lg border border-border/70 bg-card p-4">
        <label className="grid gap-2 text-sm font-medium">
          Normalized INDOT import JSON
          <input
            type="file"
            accept="application/json,.json"
            disabled={status === "running"}
            onChange={(event) => void onFileChange(event.target.files?.[0])}
            className="block w-full rounded-md border border-border bg-background px-3 py-2 text-sm"
          />
        </label>
        {fileName ? <p className="mt-2 text-xs text-muted-foreground">Selected: {fileName}</p> : null}
      </div>

      <div className="rounded-lg border border-border/70 bg-card p-4">
        <div className="grid gap-3 sm:grid-cols-3">
          <Stat label="Rows ready" value={rows.length.toLocaleString()} />
          <Stat label="Batches" value={batchCount.toLocaleString()} />
          <Stat label="Source rejects" value={rejectedCount === null ? "—" : rejectedCount.toLocaleString()} />
        </div>

        <div className="mt-4 h-2 overflow-hidden rounded-full bg-muted">
          <div className="h-full bg-foreground transition-all" style={{ width: `${progress}%` }} />
        </div>
        <p className="mt-2 text-sm text-muted-foreground">{message}</p>

        <button
          type="button"
          onClick={() => void runImport()}
          disabled={(status !== "ready" && status !== "error") || rows.length === 0}
          className="mt-4 inline-flex min-h-11 items-center justify-center rounded-md bg-foreground px-4 py-2 text-sm font-semibold text-background disabled:cursor-not-allowed disabled:opacity-50"
        >
          {status === "running" ? "Importing…" : status === "done" ? "Import complete" : "Import to production"}
        </button>

        {status === "running" || status === "done" ? (
          <p className="mt-3 text-xs text-muted-foreground">
            Received {completed.toLocaleString()} · Upserted {upserted.toLocaleString()}
          </p>
        ) : null}
      </div>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border border-border/60 bg-muted/20 p-3">
      <div className="text-xs uppercase tracking-[0.16em] text-muted-foreground">{label}</div>
      <div className="mt-1 font-mono text-xl font-semibold tabular-nums">{value}</div>
    </div>
  );
}
