/** Priced assembly components — historical generated material-price evidence.
 * The rows remain a legacy name/unit snapshot and are not a governed canonical
 * comparison set. Use legacyAssemblyMatchAudit.ts to exclude audited
 * high-confidence false positives before any review or analysis.
 * Source: supplierPrices47802.ts (observed 2026-09-13).
 * Do not use the raw array directly for bids or automatic repricing. */
export interface PricedAssemblyComponent { componentKey: string; label: string;
  quantityPerUnit: number; supplier: string; productName: string;
  unitPrice: number; priceUnit: string; extendedCost: number; matchScore: number; }
export const PRICED_ASSEMBLY_COMPONENTS: readonly PricedAssemblyComponent[] = [
  { componentKey: "mat_contractor_bags", label: "Heavy-Duty 3-Mil 42-Gallon Contractor Trash Bags",
    quantityPerUnit: 0.025, supplier: "Lowes",
    productName: "Steelcoat 42-Gallon 3-Mil Heavy-Duty Contractor Trash Bags (50-Count)", unitPrice: 0.66,
    priceUnit: "EA", extendedCost: 0.0165,
    matchScore: 0.88 },
  { componentKey: "mat_poly_dust_containment", label: "6-Mil Polyethylene Surface Protection & Dust Sheeting",
    quantityPerUnit: 0.15, supplier: "Menards",
    productName: "6-mil Clear Polyethylene Sheeting 10 ft. x 100 ft.", unitPrice: 0.07,
    priceUnit: "SF", extendedCost: 0.0105,
    matchScore: 0.55 },
  { componentKey: "mat_aggregate_subbase_crushed_stone", label: "Compacted Crushed Stone Subbase (4 in. Depth, INDOT #53 / Dense Graded)",
    quantityPerUnit: 0.021, supplier: "JonesAndSons",
    productName: "#73 Limestone", unitPrice: 24.95,
    priceUnit: "TON", extendedCost: 0.524,
    matchScore: 0.4 },
  { componentKey: "mat_rebar_no4_grade60", label: "#4 Grade 60 Deformed Steel Rebar (1/2 in. Diameter)",
    quantityPerUnit: 2.22, supplier: "Lowes",
    productName: "#4 (1/2-in) x 10-ft Grade 60 Rebar", unitPrice: 0.9,
    priceUnit: "LF", extendedCost: 1.998,
    matchScore: 0.862 },
  { componentKey: "mat_rebar_chairs_dobies", label: "Concrete Rebar Support Chairs / 3 in. Dobie Blocks",
    quantityPerUnit: 0.25, supplier: "Menards",
    productName: "Plastic Rebar Support Chairs 2 in. (20 pk)", unitPrice: 0.5,
    priceUnit: "EA", extendedCost: 0.125,
    matchScore: 0.429 },
  { componentKey: "mat_rebar_no4_wall_grid", label: "#4 Grade 60 Rebar Grid (#4 @ 18 in. OC Vert & Horiz)",
    quantityPerUnit: 1.46, supplier: "Menards",
    productName: "#4 (1/2 in.) x 20 ft. Grade 60 Rebar", unitPrice: 0.65,
    priceUnit: "LF", extendedCost: 0.949,
    matchScore: 0.461 },
  { componentKey: "mat_anchor_bolts_half_x_ten", label: "1/2 in. x 10 in. Hot-Dipped Galvanized Anchor J-Bolts w/ Nut & Washer",
    quantityPerUnit: 0.021, supplier: "Menards",
    productName: "1/2 in. x 10 in. Galvanized Anchor Bolt w/ Nut & Washer", unitPrice: 3.28,
    priceUnit: "EA", extendedCost: 0.0689,
    matchScore: 0.733 },
  { componentKey: "mat_sonotube_12in_form", label: "12 in. Diameter Heavy-Duty Fiber Concrete Form Tube",
    quantityPerUnit: 4.2, supplier: "JonesAndSons",
    productName: "12\u2033 Column Form", unitPrice: 2.38,
    priceUnit: "LF", extendedCost: 9.996,
    matchScore: 0.652 },
  { componentKey: "mat_concrete_3500_pier", label: "3500 PSI Ready-Mix Concrete for Drilled Pier",
    quantityPerUnit: 0.128, supplier: "HomeDepot",
    productName: "Quikrete 80 lb. Concrete Mix", unitPrice: 5.98,
    priceUnit: "BAG", extendedCost: 0.7654,
    matchScore: 0.4 },
  { componentKey: "mat_rebar_no4_pier_vert", label: "#4 Grade 60 Deformed Steel Rebar (Vertical Cage)",
    quantityPerUnit: 12.5, supplier: "Lowes",
    productName: "#4 (1/2-in) x 10-ft Grade 60 Rebar", unitPrice: 0.9,
    priceUnit: "LF", extendedCost: 11.25,
    matchScore: 0.705 },
  { componentKey: "mat_rebar_no3_tie_hoops", label: "#3 Steel Tie Hoops (8 in. Diameter)",
    quantityPerUnit: 6.9, supplier: "JonesAndSons",
    productName: "#3 Rebar 3/8\u2033 x 20\u2032", unitPrice: 0.3,
    priceUnit: "LF", extendedCost: 2.07,
    matchScore: 0.5 },
  { componentKey: "mat_anchor_jbolt_half_x_twelve", label: "1/2 in. x 12 in. Hot-Dipped Galvanized Anchor J-Bolt w/ Nut & Washer",
    quantityPerUnit: 1.0, supplier: "Menards",
    productName: "1/2 in. x 10 in. Galvanized Anchor Bolt w/ Nut & Washer", unitPrice: 3.28,
    priceUnit: "EA", extendedCost: 3.28,
    matchScore: 0.733 },
  { componentKey: "mat_sill_seal_gasket", label: "5-1/2 in. Polyethylene Foam Sill Seal Gasket",
    quantityPerUnit: 0.138, supplier: "Niehaus",
    productName: "Owens Corning FoamSealR 5-1/2 in. x 50 ft. Sill Plate Gasket Roll", unitPrice: 0.2,
    priceUnit: "LF", extendedCost: 0.0276,
    matchScore: 0.752 },
  { componentKey: "mat_joists_2x10_spf", label: "2x10 #2/Btr SPF Dimension Lumber (Joists & Rim)",
    quantityPerUnit: 0.92, supplier: "Niehaus",
    productName: "2 in. x 4 in. x 8 ft. #2 & Better Grade SPF Dimensional Lumber", unitPrice: 0.52,
    priceUnit: "LF", extendedCost: 0.4784,
    matchScore: 0.45 },
  { componentKey: "mat_joist_hangers_simpson", label: "Simpson Strong-Tie LUS210 Galvanized Joist Hangers",
    quantityPerUnit: 0.065, supplier: "HomeDepot",
    productName: "Simpson Strong-Tie LUC Galvanized Face-Mount Joist Hanger for 2x6", unitPrice: 1.98,
    priceUnit: "EA", extendedCost: 0.1287,
    matchScore: 0.636 },
  { componentKey: "mat_sheathing_34_tg_osb", label: "23/32 in. (3/4 in.) 4x8 Tongue-and-Groove OSB Subfloor Panels",
    quantityPerUnit: 1.08, supplier: "HomeDepot",
    productName: "23/32 in. x 4 ft. x 8 ft. Tongue and Groove OSB Subfloor", unitPrice: 0.81,
    priceUnit: "SF", extendedCost: 0.8748,
    matchScore: 0.76 },
  { componentKey: "mat_adhesive_subfloor_heavy_duty", label: "Heavy-Duty Polyurethane Subfloor Construction Adhesive (28 oz Cartridge)",
    quantityPerUnit: 0.012, supplier: "HomeDepot",
    productName: "Liquid Nails 28 oz. Heavy Duty Extreme Polyurethane/Subfloor Adhesive", unitPrice: 8.98,
    priceUnit: "EA", extendedCost: 0.1078,
    matchScore: 0.893 },
  { componentKey: "mat_rafters_2x8_spf", label: "2x8 #2/Btr SPF Dimension Lumber (Rafters)",
    quantityPerUnit: 0.82, supplier: "Niehaus",
    productName: "2 in. x 4 in. x 8 ft. #2 & Better Grade SPF Dimensional Lumber", unitPrice: 0.52,
    priceUnit: "LF", extendedCost: 0.4264,
    matchScore: 0.5 },
  { componentKey: "mat_ridge_board_2x10", label: "2x10 #2/Btr SPF Continuous Ridge Board Lumber",
    quantityPerUnit: 0.055, supplier: "Niehaus",
    productName: "2 in. x 4 in. x 8 ft. #2 & Better Grade SPF Dimensional Lumber", unitPrice: 0.52,
    priceUnit: "LF", extendedCost: 0.0286,
    matchScore: 0.45 },
  { componentKey: "fast_hurricane_clips_simpson", label: "Simpson Strong-Tie H2.5A Hurricane Ties w/ 8d x 1-1/2 in. Nails",
    quantityPerUnit: 0.75, supplier: "HomeDepot",
    productName: "Simpson Strong-Tie H2.5A Galvanized Hurricane Tie", unitPrice: 1.38,
    priceUnit: "EA", extendedCost: 1.035,
    matchScore: 0.55 },
  { componentKey: "mat_deck_joists_2x8_pt", label: "2x8 #2 Pressure-Treated Pine Deck Joists (16 in. OC)",
    quantityPerUnit: 0.88, supplier: "Lowes",
    productName: "Severe Weather 5/4-in x 6-in x 16-ft Standard Pressure Treated Deck Board", unitPrice: 0.94,
    priceUnit: "LF", extendedCost: 0.8272,
    matchScore: 0.587 },
  { componentKey: "mat_deck_beams_2x10_pt", label: "Double 2x10 #2 Pressure-Treated Pine Carrying Beam Lumber",
    quantityPerUnit: 0.22, supplier: "HomeDepot",
    productName: "2 in. x 8 in. x 8 ft. #2 Ground Contact Pressure-Treated Southern Yellow Pine Lu", unitPrice: 1.69,
    priceUnit: "LF", extendedCost: 0.3718,
    matchScore: 0.525 },
  { componentKey: "mat_deck_posts_6x6_pt", label: "6x6 #2 Ground-Contact Pressure-Treated Support Posts",
    quantityPerUnit: 0.05, supplier: "HomeDepot",
    productName: "6 in. x 6 in. x 8 ft. #2 Ground Contact Pressure-Treated Timber", unitPrice: 4.62,
    priceUnit: "LF", extendedCost: 0.231,
    matchScore: 0.588 },
  { componentKey: "fast_deck_hardware_hangers", label: "Simpson Strong-Tie ZMAX Joist Hangers & H2.5AZ Ties w/ HDG Screws",
    quantityPerUnit: 0.15, supplier: "Lowes",
    productName: "Simpson Strong-Tie H2.5A 18-Gauge ZMAX Hurricane Tie", unitPrice: 1.48,
    priceUnit: "EA", extendedCost: 0.222,
    matchScore: 0.442 },
  { componentKey: "fast_ledger_structural_screws", label: "1/2 in. x 5 in. Heavy-Duty Exterior Structural Wood Screws (FastenMaster LedgerL",
    quantityPerUnit: 0.08, supplier: "Lowes",
    productName: "FastenMaster HeadLOK 4-1/2-in Structural Wood Screws (50-Pack)", unitPrice: 0.8,
    priceUnit: "EA", extendedCost: 0.064,
    matchScore: 0.681 },
  { componentKey: "mat_deck_boards_54x6_pt", label: "5/4 in. x 6 in. Premium Pressure-Treated Pine Decking Lumber",
    quantityPerUnit: 2.4, supplier: "HomeDepot",
    productName: "5/4 in. x 6 in. x 8 ft. Standard Ground Contact Pressure-Treated Southern Yellow", unitPrice: 0.79,
    priceUnit: "LF", extendedCost: 1.896,
    matchScore: 0.668 },
  { componentKey: "mat_deck_boards_composite_grooved", label: "1 in. x 5-1/2 in. Capped Composite Grooved Decking Boards",
    quantityPerUnit: 2.36, supplier: "HomeDepot",
    productName: "Trex Enhance Basics Clam Shell 1 in. x 5.5 in. x 12 ft. Grooved Edge Composite D", unitPrice: 2.29,
    priceUnit: "LF", extendedCost: 5.4044,
    matchScore: 0.537 },
  { componentKey: "mat_butyl_joist_tape", label: "Self-Adhesive Butyl Joist Flashing Tape (1-5/8 in. Width)",
    quantityPerUnit: 0.82, supplier: "Menards",
    productName: "Deck Joist Butyl Protective Flashing Tape 1-5/8 in. x 50 ft.", unitPrice: 0.34,
    priceUnit: "LF", extendedCost: 0.2788,
    matchScore: 0.681 },
  { componentKey: "mat_guard_posts_4x4_pt", label: "4x4 #2 Pressure-Treated Pine Guard Posts (48 in. Length)",
    quantityPerUnit: 0.2, supplier: "HomeDepot",
    productName: "2 in. x 8 in. x 8 ft. #2 Ground Contact Pressure-Treated Southern Yellow Pine Lu", unitPrice: 1.69,
    priceUnit: "LF", extendedCost: 0.338,
    matchScore: 0.42 },
  { componentKey: "mat_rails_2x4_pt", label: "2x4 #2 Pressure-Treated Pine Top & Bottom Sub-Rails",
    quantityPerUnit: 2.2, supplier: "HomeDepot",
    productName: "2 in. x 8 in. x 8 ft. #2 Ground Contact Pressure-Treated Southern Yellow Pine Lu", unitPrice: 1.69,
    priceUnit: "LF", extendedCost: 3.718,
    matchScore: 0.42 },
  { componentKey: "fast_post_thru_bolts_half_x_eight", label: "1/2 in. x 8 in. Hot-Dipped Galvanized Carriage / Thru-Bolts w/ Washers",
    quantityPerUnit: 0.4, supplier: "Menards",
    productName: "1/2 in. x 8 in. Galvanized Carriage Bolts w/ Nuts (10 pk)", unitPrice: 2.0,
    priceUnit: "EA", extendedCost: 0.8,
    matchScore: 0.655 },
  { componentKey: "mat_shingles_architectural_bundles", label: "Laminated Architectural Asphalt Shingles (3 Bundles/SQ)",
    quantityPerUnit: 3.3, supplier: "HomeDepot",
    productName: "GAF Timberline HDZ Charcoal Algae Resistant Laminated Shingles (33.33 sq. ft. / ", unitPrice: 116.94,
    priceUnit: "EA", extendedCost: 385.902,
    matchScore: 0.7 },
  { componentKey: "mat_shingles_hip_ridge_cap", label: "Matching Perforated Hip & Ridge Cap Shingles",
    quantityPerUnit: 0.15, supplier: "HomeDepot",
    productName: "GAF Seal-A-Ridge Charcoal Hip and Ridge Cap Asphalt Shingles (25 lin. ft. per Bu", unitPrice: 2.2,
    priceUnit: "LF", extendedCost: 0.33,
    matchScore: 0.567 },
  { componentKey: "fast_plastic_cap_nails_1in", label: "1 in. Plastic-Cap Electro-Galvanized Roofing Nails",
    quantityPerUnit: 32.0, supplier: "Menards",
    productName: "Plastic Cap Roofing & Underlayment Nails 1-1/4 in. (3,000 ct)", unitPrice: 0.01,
    priceUnit: "EA", extendedCost: 0.32,
    matchScore: 0.65 },
  { componentKey: "mat_membrane_ice_water_roll", label: "Self-Adhering Rubberized Asphalt Ice & Water Membrane (2 SQ Roll)",
    quantityPerUnit: 0.55, supplier: "Menards",
    productName: "Grip-Rite Polyset Self-Adhering Ice & Water (2 SQ)", unitPrice: 37.49,
    priceUnit: "SQ", extendedCost: 20.6195,
    matchScore: 0.62 },
  { componentKey: "mat_drip_edge_metal_10ft", label: "Painted Aluminum T-Style / Eave Drip Edge (10 ft Length)",
    quantityPerUnit: 0.108, supplier: "Menards",
    productName: "Aluminum T-Style Drip Edge 10 ft. Bronze / Brown", unitPrice: 0.7,
    priceUnit: "LF", extendedCost: 0.0756,
    matchScore: 0.723 },
  { componentKey: "mat_siding_starter_strip", label: "Galvanized Steel / Vinyl Siding Starter Strip (10 ft Length)",
    quantityPerUnit: 0.12, supplier: "Lowes",
    productName: "Style Crest 10-ft Galvanized Steel Vinyl Siding Starter Strip", unitPrice: 0.6,
    priceUnit: "LF", extendedCost: 0.072,
    matchScore: 0.862 },
  { componentKey: "mat_siding_jchannel_trim", label: "3/4 in. Vinyl J-Channel Trim (12.5 ft Length)",
    quantityPerUnit: 0.35, supplier: "HomeDepot",
    productName: "Ply Gem 3/4 in. x 12 ft. 6 in. White Vinyl J-Channel", unitPrice: 0.64,
    priceUnit: "LF", extendedCost: 0.224,
    matchScore: 0.76 },
  { componentKey: "fast_cap_staples_stinger", label: "1 in. Plastic-Cap Pneumatic Staples / Hand Cap Nails",
    quantityPerUnit: 40.0, supplier: "Menards",
    productName: "Plastic Cap Roofing & Underlayment Nails 1-1/4 in. (3,000 ct)", unitPrice: 0.01,
    priceUnit: "EA", extendedCost: 0.4,
    matchScore: 0.52 },
  { componentKey: "mat_soffit_vent_baffles", label: "Extruded Polystyrene / Cardboard Attic Soffit Air Baffles / Raft-R-Mate",
    quantityPerUnit: 0.03, supplier: "Menards",
    productName: "Owens Corning Raft-R-Mate Attic Rafter Baffle", unitPrice: 2.48,
    priceUnit: "EA", extendedCost: 0.0744,
    matchScore: 0.43 },
  { componentKey: "mat_door_prehung_hc_unit", label: "Molded Composite Hollow-Core Prehung Interior Door Unit w/ Hinges",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "JELD-WEN 32 in. x 80 in. Colonist Primed Left-Hand Hollow Core Prehung Door", unitPrice: 134.0,
    priceUnit: "EA", extendedCost: 134.0,
    matchScore: 0.45 },
  { componentKey: "mat_hardware_knobset_passage", label: "Standard Passage / Privacy Cylindrical Door Knob / Lever Set",
    quantityPerUnit: 1.0, supplier: "Menards",
    productName: "Passage Interior Door Knob (Satin Nickel)", unitPrice: 14.98,
    priceUnit: "EA", extendedCost: 14.98,
    matchScore: 0.412 },
  { componentKey: "mat_foam_low_expansion_window", label: "Low-Pressure Minimal-Expansion Polyurethane Window & Door Foam (12 oz Can)",
    quantityPerUnit: 0.5, supplier: "Lowes",
    productName: "Great Stuff Window and Door 12-oz Polyurethane Insulating Foam Sealant", unitPrice: 6.98,
    priceUnit: "EA", extendedCost: 3.49,
    matchScore: 0.709 },
  { componentKey: "mat_drywall_board_half_wall", label: "1/2 in. x 4x12 Gypsum Wallboard Panels (ASTM C1396)",
    quantityPerUnit: 1.1, supplier: "HomeDepot",
    productName: "USG Sheetrock Brand 1/2 in. x 4 ft. x 8 ft. UltraLight Drywall Panel", unitPrice: 0.47,
    priceUnit: "SF", extendedCost: 0.517,
    matchScore: 0.442 },
  { componentKey: "mat_joint_tape_paper", label: "Cross-Fiber Joint Paper Tape (ASTM C475)",
    quantityPerUnit: 1.045, supplier: "Menards",
    productName: "Drywall Paper Joint Tape (250 ft)", unitPrice: 0.02,
    priceUnit: "LF", extendedCost: 0.0209,
    matchScore: 0.45 },
  { componentKey: "mat_corner_bead_vinyl_metal", label: "Vinyl / Paper-Faced Metal Outside Corner Bead",
    quantityPerUnit: 0.12, supplier: "HomeDepot",
    productName: "USG Sheetrock Brand 8 ft. Paper-Faced Metal Corner Bead", unitPrice: 0.43,
    priceUnit: "LF", extendedCost: 0.0516,
    matchScore: 0.75 },
  { componentKey: "mat_drywall_board_half_ceiling", label: "1/2 in. x 4x12 Sag-Resistant Interior Gypsum Ceiling Board (ASTM C1396)",
    quantityPerUnit: 1.12, supplier: "Menards",
    productName: "1/2 in. x 4 ft. x 8 ft. Sag-Resistant Ceiling Drywall", unitPrice: 0.48,
    priceUnit: "SF", extendedCost: 0.5376,
    matchScore: 0.485 },
  { componentKey: "mat_joint_tape_paper_ceil", label: "Cross-Fiber Joint Paper Tape (ASTM C475)",
    quantityPerUnit: 1.1, supplier: "Menards",
    productName: "Drywall Paper Joint Tape (250 ft)", unitPrice: 0.02,
    priceUnit: "LF", extendedCost: 0.022,
    matchScore: 0.45 },
  { componentKey: "mat_drywall_typex_58_board", label: "5/8 in. x 4x12 Type X Fire-Rated Gypsum Board (ASTM C1396)",
    quantityPerUnit: 1.1, supplier: "Lowes",
    productName: "5/8-in 4x12 Type X Fire-Rated Drywall Panel", unitPrice: 0.59,
    priceUnit: "SF", extendedCost: 0.649,
    matchScore: 0.645 },
  { componentKey: "mat_joint_tape_paper_fire", label: "Cross-Fiber Joint Paper Tape (ASTM C475)",
    quantityPerUnit: 1.1, supplier: "Menards",
    productName: "Drywall Paper Joint Tape (250 ft)", unitPrice: 0.02,
    priceUnit: "LF", extendedCost: 0.022,
    matchScore: 0.45 },
  { componentKey: "mat_compound_setting_type", label: "Setting-Type Joint Compound (USG Sheetrock Easy Sand 20/45)",
    quantityPerUnit: 0.1, supplier: "HomeDepot",
    productName: "USG Sheetrock Brand Easy Sand 45 18 lb. Lightweight Setting-Type Joint Compound", unitPrice: 0.94,
    priceUnit: "LB", extendedCost: 0.094,
    matchScore: 0.823 },
  { componentKey: "mat_tape_fiberglass_mesh", label: "Self-Adhering Fiberglass Mesh Joint Tape (2 in. Width)",
    quantityPerUnit: 5.5, supplier: "HomeDepot",
    productName: "FibaTape 150 ft. Self-Adhesive Fiberglass Mesh Drywall Joint Tape", unitPrice: 0.04,
    priceUnit: "LF", extendedCost: 0.22,
    matchScore: 0.545 },
  { componentKey: "mat_paint_interior_latex_gal", label: "Premium Interior Acrylic Latex Wall Paint (Eggshell/Satin)",
    quantityPerUnit: 0.0062, supplier: "Lowes",
    productName: "Valspar 2000 Interior Eggshell Bright White Latex Paint (1-Gallon)", unitPrice: 28.98,
    priceUnit: "GAL", extendedCost: 0.1797,
    matchScore: 0.459 },
  { componentKey: "mat_masking_tape_blue_15", label: "1.5 in. Edge-Lock Blue Painter's Masking Tape (60 yd Roll)",
    quantityPerUnit: 0.0018, supplier: "Menards",
    productName: "FrogTape Multi-Surface Green Painter's Tape (60 yd)", unitPrice: 0.05,
    priceUnit: "LF", extendedCost: 0.0001,
    matchScore: 0.458 },
  { componentKey: "mat_roller_tray_sleeve", label: "9 in. x 3/8 in. Microfiber Roller Sleeve & Tray Liner Allocation",
    quantityPerUnit: 0.0013, supplier: "Lowes",
    productName: "Purdy Marathon 3-Pack 9-in x 3/8-in Knit Paint Roller Covers", unitPrice: 4.99,
    priceUnit: "EA", extendedCost: 0.0065,
    matchScore: 0.42 },
  { componentKey: "mat_primer_pva_drywall_gal", label: "High-Solids Polyvinyl Acetate (PVA) Drywall Primer / Sealer",
    quantityPerUnit: 0.0037, supplier: "Lowes",
    productName: "Valspar Professional Drywall PVA White Primer and Sealer (5-Gallon)", unitPrice: 13.0,
    priceUnit: "GAL", extendedCost: 0.0481,
    matchScore: 0.45 },
  { componentKey: "mat_paint_interior_latex_gal", label: "Premium Interior Acrylic Latex Finish Paint",
    quantityPerUnit: 0.0062, supplier: "HomeDepot",
    productName: "Behr Premium Plus 1 Gal. Ultra Pure White Flat Exterior Paint & Primer", unitPrice: 38.98,
    priceUnit: "GAL", extendedCost: 0.2417,
    matchScore: 0.552 },
  { componentKey: "mat_paint_ceiling_flat_gal", label: "Dead-Flat Interior Latex Ceiling White Paint",
    quantityPerUnit: 0.0062, supplier: "HomeDepot",
    productName: "Behr Pro 5 Gal. White Interior Dead Flat Ceiling Paint", unitPrice: 19.8,
    priceUnit: "GAL", extendedCost: 0.1228,
    matchScore: 0.75 },
  { componentKey: "mat_roller_sleeve_half_nap", label: "9 in. x 1/2 in. High-Capacity Microfiber / Knit Roller Sleeve",
    quantityPerUnit: 0.0015, supplier: "JonesAndSons",
    productName: "Firebrick Split 1-1/4\"", unitPrice: 2.45,
    priceUnit: "EA", extendedCost: 0.0037,
    matchScore: 0.444 },
  { componentKey: "mat_lvp_planks_click_lock", label: "Rigid Core Click-Lock Luxury Vinyl Plank w/ Attached Pad (20-Mil Wear Layer)",
    quantityPerUnit: 1.1, supplier: "HomeDepot",
    productName: "LifeProof Walton Oak 8.7 in. W x 47.6 in. L Click Lock Luxury Vinyl Plank Floori", unitPrice: 3.2,
    priceUnit: "SF", extendedCost: 3.52,
    matchScore: 0.562 },
  { componentKey: "mat_poly_vapor_barrier_slab", label: "6-Mil Polyethylene Moisture Barrier Sheeting (Concrete Slabs Only)",
    quantityPerUnit: 1.14, supplier: "JonesAndSons",
    productName: "20\u2032 x 100\u2032 Clear Plastic Sheeting 6 Mil", unitPrice: 0.04,
    priceUnit: "SF", extendedCost: 0.0456,
    matchScore: 0.514 },
  { componentKey: "mat_tack_strip_wood_residential", label: "Architectural Wood Tack Strip Strips (1 in. Width, 4 ft Length)",
    quantityPerUnit: 0.28, supplier: "Menards",
    productName: "1 x 2 x 8 ft. Furring Strip", unitPrice: 0.25,
    priceUnit: "LF", extendedCost: 0.07,
    matchScore: 0.43 },
  { componentKey: "mat_seaming_tape_hotmelt", label: "3 in. Hot-Melt Thermoseal Carpet Seaming Tape",
    quantityPerUnit: 0.08, supplier: "Niehaus",
    productName: "REX 3 In. x 165 Ft. White Seaming Tape", unitPrice: 0.15,
    priceUnit: "LF", extendedCost: 0.012,
    matchScore: 0.4 },
  { componentKey: "mat_tile_porcelain_12x24", label: "12 in. x 24 in. Rectified Porcelain Floor Tile (Grade 1)",
    quantityPerUnit: 1.1, supplier: "Lowes",
    productName: "Style Selections 12-in x 24-in Matte Porcelain Floor and Wall Tile (16-sq ft)", unitPrice: 1.99,
    priceUnit: "SF", extendedCost: 2.189,
    matchScore: 0.553 },
  { componentKey: "mat_mortar_thinset_modified_50lb", label: "Polymer-Modified Large & Heavy Tile Mortar (ANSI A118.4/11, 50 lb Bag)",
    quantityPerUnit: 0.024, supplier: "JonesAndSons",
    productName: "Tamms Thin Patch 50# Bag", unitPrice: 43.12,
    priceUnit: "BAG", extendedCost: 1.0349,
    matchScore: 0.503 },
  { componentKey: "mat_grout_sanded_universal_25lb", label: "Polymer-Modified Universal / Sanded Tile Grout (25 lb Bag)",
    quantityPerUnit: 0.007, supplier: "Lowes",
    productName: "MAPEI Keracolor S 25-lb Warm Gray Sanded Grout", unitPrice: 0.72,
    priceUnit: "LB", extendedCost: 0.005,
    matchScore: 0.63 },
  { componentKey: "mat_cement_board_half_3x5", label: "1/2 in. x 3 ft x 5 ft Cementitious Backer Unit Panels (ANSI A118.9)",
    quantityPerUnit: 1.08, supplier: "Menards",
    productName: "1/2 in. x 3 ft. x 5 ft. ft. x 5 ft. Durock Cement Backer Board", unitPrice: 1.0,
    priceUnit: "SF", extendedCost: 1.08,
    matchScore: 0.55 },
  { componentKey: "mat_mortar_thinset_bed_cbu", label: "Modified Thin-Set Mortar for Subfloor Bedding (50 lb Bag)",
    quantityPerUnit: 0.015, supplier: "JonesAndSons",
    productName: "Tamms Thin Patch 50# Bag", unitPrice: 43.12,
    priceUnit: "BAG", extendedCost: 0.6468,
    matchScore: 0.647 },
  { componentKey: "fast_cbu_screws_alkali_125", label: "1-1/4 in. #8 Star-Drive Alkali-Resistant Cement Board Screws",
    quantityPerUnit: 1.85, supplier: "HomeDepot",
    productName: "Rock-On #8 x 1-1/4 in. Star Drive Cement Board Screws (750-Pack)", unitPrice: 0.04,
    priceUnit: "EA", extendedCost: 0.074,
    matchScore: 0.731 },
  { componentKey: "mat_tape_cbu_alkali_mesh", label: "2 in. Alkali-Resistant Self-Adhering Fiberglass Mesh Tape",
    quantityPerUnit: 0.85, supplier: "Menards",
    productName: "Fiberglass Self-Adhesive Drywall Mesh Tape (300 ft)", unitPrice: 0.03,
    priceUnit: "LF", extendedCost: 0.0255,
    matchScore: 0.5 },
  { componentKey: "mat_baseboard_4in_mdf_primed", label: "3-1/4 in. to 4-1/4 in. Pre-Primed MDF / Finger-Joint Pine Baseboard (16 ft Lengt",
    quantityPerUnit: 1.1, supplier: "Lowes",
    productName: "RELIABILT 3.25-in x 8-ft Primed Pine Baseboard Moulding", unitPrice: 1.44,
    priceUnit: "LF", extendedCost: 1.584,
    matchScore: 0.692 },
  { componentKey: "fast_finish_nails_16ga_25", label: "2-1/2 in. 16-Gauge Galvanized Finish Nails",
    quantityPerUnit: 1.5, supplier: "HomeDepot",
    productName: "DeWalt 2-1/2 in. x 16-Gauge Galvanized Straight Finish Nails (2,500-Pack)", unitPrice: 0.01,
    priceUnit: "EA", extendedCost: 0.015,
    matchScore: 0.862 },
  { componentKey: "mat_door_casing_primed_mdf", label: "2-1/4 in. to 3-1/2 in. Pre-Primed MDF / Pine Door Casing Moulding",
    quantityPerUnit: 1.1, supplier: "Lowes",
    productName: "Metrie 2.25-in x 7-ft Primed MDF Casing Moulding", unitPrice: 0.85,
    priceUnit: "LF", extendedCost: 0.935,
    matchScore: 0.694 },
  { componentKey: "fast_casing_nails_finish", label: "2-1/2 in. 16ga Stud Nails & 1-1/4 in. 18ga Brad Nails",
    quantityPerUnit: 2.0, supplier: "Menards",
    productName: "15-Gauge DA Angled Finish Nails 2-1/2 in. (4,000 ct)", unitPrice: 0.01,
    priceUnit: "EA", extendedCost: 0.02,
    matchScore: 0.459 },
  { componentKey: "fast_cabinet_screws_grk_3in", label: "#10 x 3 in. Heavy-Duty Washer-Head Cabinet Hanging Screws (GRK / FastenMaster)",
    quantityPerUnit: 4.0, supplier: "Lowes",
    productName: "FastenMaster HeadLOK 2-7/8-in Structural Wood Screws (50-Pack)", unitPrice: 0.6,
    priceUnit: "EA", extendedCost: 2.4,
    matchScore: 0.425 },
  { componentKey: "fast_face_frame_screws_trim", label: "#8 x 2-1/2 in. Trim-Head Face Frame Joining Screws",
    quantityPerUnit: 4.0, supplier: "Menards",
    productName: "1/2 in. x 8 in. Galvanized Hex Lag Screws (25 pk)", unitPrice: 1.2,
    priceUnit: "EA", extendedCost: 4.8,
    matchScore: 0.444 },
  { componentKey: "mat_shims_composite_cabinet", label: "Heavy-Duty Composite Leveling Shims (Pack Allocation)",
    quantityPerUnit: 0.25, supplier: "Lowes",
    productName: "Beddar Shims 8-in Composite Shims (12-Pack)", unitPrice: 0.41,
    priceUnit: "EA", extendedCost: 0.1025,
    matchScore: 0.688 },
  { componentKey: "mat_toilet_2pc_elongated_unit", label: "Two-Piece Elongated Vitreous China Toilet (1.28 GPF WaterSense)",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "Kohler Elmbrook The Complete Solution 2-Piece 1.28 GPF Single Flush Elongated To", unitPrice: 249.0,
    priceUnit: "EA", extendedCost: 249.0,
    matchScore: 0.614 },
  { componentKey: "mat_wax_ring_reinforced_sleeve", label: "Reinforced Wax Bowl Ring with Polyethylene Sleeve / Horn",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "Oatey Heavy-Duty Reinforced Wax Toilet Bowl Ring with Plastic Sleeve and Hardwar", unitPrice: 5.48,
    priceUnit: "EA", extendedCost: 5.48,
    matchScore: 0.85 },
  { componentKey: "mat_supply_line_braided_ss_toilet", label: "3/8 in. Comp x 7/8 in. Ballcock x 12 in. Braided Stainless Water Connector",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "BrassCraft 3/8 in. Compression x 7/8 in. Ballcock Nut x 12 in. Braided Polymer T", unitPrice: 6.98,
    priceUnit: "EA", extendedCost: 6.98,
    matchScore: 0.799 },
  { componentKey: "mat_faucet_kitchen_pulldown_unit", label: "Single-Handle Pull-Down Deck-Mount Kitchen Faucet w/ Integral PEX Leads",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "Moen Adler Single-Handle Pull-Down Sprayer Kitchen Faucet in Chrome", unitPrice: 119.0,
    priceUnit: "EA", extendedCost: 119.0,
    matchScore: 0.53 },
  { componentKey: "mat_sink_basin_stainless_double", label: "Stainless Steel / Granite Composite Double/Single Bowl Kitchen Sink Basin",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "Elkay Dayton Drop-In Stainless Steel 33 in. 4-Hole Double Bowl Kitchen Sink", unitPrice: 139.0,
    priceUnit: "EA", extendedCost: 139.0,
    matchScore: 0.54 },
  { componentKey: "mat_drain_tubular_waste_ptrap_kit", label: "1-1/2 in. Polypropylene Continuous Waste & Slip-Joint P-Trap Kit",
    quantityPerUnit: 1.0, supplier: "Lowes",
    productName: "Keeney 1-1/2-in White Plastic Slip-Joint P-Trap", unitPrice: 4.98,
    priceUnit: "EA", extendedCost: 4.98,
    matchScore: 0.76 },
  { componentKey: "equip_water_heater_50gal_electric", label: "50-Gallon Dual-Element Electric Storage Water Heater (240V / 4500W, 0.92 UEF)",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "Rheem Performance 50 Gal. Medium 6-Year 4500-Watt Dual Element Electric Water He", unitPrice: 549.0,
    priceUnit: "EA", extendedCost: 549.0,
    matchScore: 0.452 },
  { componentKey: "mat_drain_pan_aluminum_24in", label: "24 in. Heavy-Duty Aluminum Water Heater Drain Pan w/ 3/4 in. PVC Adapter",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "Camco 24 in. Aluminum Water Heater Drain Pan", unitPrice: 19.98,
    priceUnit: "EA", extendedCost: 19.98,
    matchScore: 0.552 },
  { componentKey: "mat_ball_valve_shutoff_34", label: "3/4 in. Full-Port Brass Ball Valve (Push-to-Connect / Sweat)",
    quantityPerUnit: 1.0, supplier: "Menards",
    productName: "3/4 in. Full Port Brass Ball Valve", unitPrice: 12.98,
    priceUnit: "EA", extendedCost: 12.98,
    matchScore: 0.79 },
  { componentKey: "mat_flex_connectors_34_stainless", label: "3/4 in. FIP x 3/4 in. Push-to-Connect Stainless Flexible Connectors (18 in. Leng",
    quantityPerUnit: 2.0, supplier: "Menards",
    productName: "Watts AquaLock 3/4 in. Push-to-Connect Coupling", unitPrice: 9.98,
    priceUnit: "EA", extendedCost: 19.96,
    matchScore: 0.451 },
  { componentKey: "mat_vent_pipe_pvc_sch40_kit", label: "2 in. / 3 in. Schedule 40 PVC Vent Pipe & Fitting Kit (Condensing Furnaces)",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "Charlotte Pipe 2 in. Schedule 40 PVC Socket Tee", unitPrice: 6.98,
    priceUnit: "EA", extendedCost: 6.98,
    matchScore: 0.506 },
  { componentKey: "mat_condensate_drain_tubing_kit", label: "3/4 in. PVC Condensate Trap & Drain Line Kit w/ Neutralizer",
    quantityPerUnit: 1.0, supplier: "Menards",
    productName: "3/4 in. Schedule 40 PVC Condensate 90\u00b0 Elbow", unitPrice: 0.78,
    priceUnit: "EA", extendedCost: 0.78,
    matchScore: 0.43 },
  { componentKey: "equip_thermostat_smart_unit", label: "Wi-Fi Smart / Digital Programmable Thermostat Unit w/ Trim Plate",
    quantityPerUnit: 1.0, supplier: "Lowes",
    productName: "Honeywell Home T6 Pro Wi-Fi Programmable Thermostat", unitPrice: 119.0,
    priceUnit: "EA", extendedCost: 119.0,
    matchScore: 0.517 },
  { componentKey: "mat_receptacle_duplex_tr_15a", label: "15A 125V Tamper-Resistant Duplex Receptacle (Decora or Traditional)",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "Leviton Decora 15 Amp Tamper-Resistant Duplex Outlet in White (10-Pack)", unitPrice: 2.5,
    priceUnit: "EA", extendedCost: 2.5,
    matchScore: 0.514 },
  { componentKey: "mat_wall_plate_1gang_nylon", label: "1-Gang Unbreakable Thermoplastic Nylon Wall Plate",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "Leviton 1-Gang Midway Blank Wall Plate in White (10-Pack)", unitPrice: 0.8,
    priceUnit: "EA", extendedCost: 0.8,
    matchScore: 0.636 },
  { componentKey: "mat_wire_pigtail_conductors", label: "12 AWG / 14 AWG Solid Copper Pigtail Conductors (Hot, Neutral, Ground)",
    quantityPerUnit: 1.5, supplier: "Menards",
    productName: "12 AWG Solid THHN Copper Wire Black (500 ft.)", unitPrice: 0.18,
    priceUnit: "LF", extendedCost: 0.27,
    matchScore: 0.413 },
  { componentKey: "fast_twist_wire_connectors", label: "Twist-On Wire Connectors (Tan / Yellow / Red / WAGO Lever)",
    quantityPerUnit: 3.0, supplier: "Lowes",
    productName: "WAGO 221-413 Compact Splicing Wire Connectors 3-Conductor (50-Pack)", unitPrice: 0.5,
    priceUnit: "EA", extendedCost: 1.5,
    matchScore: 0.403 },
  { componentKey: "mat_wire_ground_pigtail_bare", label: "14 AWG Bare / Green Ground Pigtail Conductor w/ Grounding Screw",
    quantityPerUnit: 0.5, supplier: "Menards",
    productName: "14 AWG Solid THHN Ground Wire Green (500 ft.)", unitPrice: 0.12,
    priceUnit: "LF", extendedCost: 0.06,
    matchScore: 0.413 },
  { componentKey: "fast_wire_nuts_twist_switch", label: "Twist-On Wire Connectors (Orange / Yellow)",
    quantityPerUnit: 2.0, supplier: "HomeDepot",
    productName: "Ideal Wing-Nut Wire Connectors Yellow (100-Pack)", unitPrice: 0.15,
    priceUnit: "EA", extendedCost: 0.3,
    matchScore: 0.44 },
  { componentKey: "mat_wafer_led_light_6in", label: "6 in. Round Slim Canless Recessed LED Wafer Downlight (Selectable CCT, IC Rated)",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "Commercial Electric 6 in. Selectable CCT Integrated LED Canless Recessed Light T", unitPrice: 10.0,
    priceUnit: "EA", extendedCost: 10.0,
    matchScore: 0.694 },
  { componentKey: "mat_wire_nm_jumper_14_2", label: "NM-B 14/2 w/ Ground Copper Romex Jumper Cable",
    quantityPerUnit: 8.0, supplier: "HomeDepot",
    productName: "Southwire 250 ft. 14/2 Solid Romex SIMpull CU NM-B W/G Wire", unitPrice: 0.32,
    priceUnit: "LF", extendedCost: 2.56,
    matchScore: 0.701 },
  { componentKey: "equip_breaker_20a_single_pole", label: "20A 120V Single-Pole Circuit Breaker (Standard / AFCI / GFCI)",
    quantityPerUnit: 1.0, supplier: "HomeDepot",
    productName: "Square D Homeline 15 Amp Single-Pole Circuit Breaker", unitPrice: 7.98,
    priceUnit: "EA", extendedCost: 7.98,
    matchScore: 0.525 },
  { componentKey: "mat_cable_nmb_12_2_copper", label: "NM-B 12/2 w/ Ground Non-Metallic Sheathed Copper Cable (90 deg C)",
    quantityPerUnit: 58.0, supplier: "Lowes",
    productName: "Southwire Romex SIMpull 100-ft 12/2 Non-Metallic Wire", unitPrice: 0.55,
    priceUnit: "LF", extendedCost: 31.9,
    matchScore: 0.5 },
  { componentKey: "fast_cable_staples_insulated", label: "1/2 in. Plastic Insulated Metal Cable Staples",
    quantityPerUnit: 14.0, supplier: "Lowes",
    productName: "Gardner Bender 1/2-in Insulated Metal Cable Staples (100-Pack)", unitPrice: 0.06,
    priceUnit: "EA", extendedCost: 0.84,
    matchScore: 0.78 },
  { componentKey: "mat_nail_safety_plates_steel", label: "1-1/2 in. x 2-1/2 in. 16-Gauge Steel Stud Protection Nail Plates",
    quantityPerUnit: 4.0, supplier: "Menards",
    productName: "Steel Stud Nail Safety Protector Plates (50 pk)", unitPrice: 0.3,
    priceUnit: "EA", extendedCost: 1.2,
    matchScore: 0.461 },
  { componentKey: "mat_truss_tie_down_clips", label: "Simpson Strong-Tie H2.5A Galvanized Hurricane Ties w/ 8d x 1-1/2 in. Nails",
    quantityPerUnit: 0.088, supplier: "HomeDepot",
    productName: "Simpson Strong-Tie H2.5A Galvanized Hurricane Tie", unitPrice: 1.38,
    priceUnit: "EA", extendedCost: 0.1214,
    matchScore: 0.61 },
  { componentKey: "mat_osb_sheathing_716_4x8", label: "7/16 in. (15/32 in.) 4x8 Structural 1 APA Rated OSB Sheathing Panels",
    quantityPerUnit: 1.08, supplier: "Niehaus",
    productName: "1/2 in. x 4 ft. x 8 ft OSB Sheathing", unitPrice: 0.45,
    priceUnit: "SF", extendedCost: 0.486,
    matchScore: 0.442 },
  { componentKey: "mat_plywood_cdx_12_4x8", label: "15/32 in. (1/2 in.) 4x8 4-Ply / 5-Ply CDX APA Structural 1 Plywood Sheathing",
    quantityPerUnit: 1.1, supplier: "HomeDepot",
    productName: "15/32 in. x 4 ft. x 8 ft. 3-Ply CDX Pine Plywood", unitPrice: 0.78,
    priceUnit: "SF", extendedCost: 0.858,
    matchScore: 0.692 },
  { componentKey: "mat_lvl_beam_member_1178", label: "1-3/4 in. x 11-7/8 in. 2.0E 3100Fb Laminated Veneer Lumber (LVL) Plies",
    quantityPerUnit: 2.12, supplier: "HomeDepot",
    productName: "1-3/4 in. x 11-7/8 in. x 16 ft. 2.0E LVL Beam", unitPrice: 7.75,
    priceUnit: "LF", extendedCost: 16.43,
    matchScore: 0.84 },
  { componentKey: "fast_structural_screws_lvl_sdws", label: "FastenMaster FlatLOK / Simpson SDWS 3-1/2 in. Multi-Ply Structural Screws",
    quantityPerUnit: 2.16, supplier: "Niehaus",
    productName: "Simpson Strong-Tie SD9112 #9 x 1-1/2 in. Structural Connector Screws (100-Pack)", unitPrice: 0.15,
    priceUnit: "EA", extendedCost: 0.324,
    matchScore: 0.443 },
  { componentKey: "fast_column_cap_connectors", label: "Simpson Strong-Tie CC44 / AC4Z Galvanized Column Post Caps & Hardware",
    quantityPerUnit: 0.1, supplier: "HomeDepot",
    productName: "Simpson Strong-Tie ABA ZMAX Galvanized Adjustable Standoff Post Base for 4x4", unitPrice: 8.98,
    priceUnit: "EA", extendedCost: 0.898,
    matchScore: 0.475 },
  { componentKey: "mat_stringer_lumber_2x12_pt", label: "2x12 #2 Ground-Contact Pressure-Treated Pine Stringer Lumber",
    quantityPerUnit: 3.55, supplier: "HomeDepot",
    productName: "2 in. x 8 in. x 8 ft. #2 Ground Contact Pressure-Treated Southern Yellow Pine Lu", unitPrice: 1.69,
    priceUnit: "LF", extendedCost: 5.9995,
    matchScore: 0.735 },
  { componentKey: "mat_tread_boards_54x6_pt", label: "5/4 in. x 6 in. Premium Radius-Edge Pressure-Treated Decking (2 per Tread)",
    quantityPerUnit: 6.48, supplier: "HomeDepot",
    productName: "5/4 in. x 6 in. x 8 ft. Standard Ground Contact Pressure-Treated Southern Yellow", unitPrice: 0.79,
    priceUnit: "LF", extendedCost: 5.1192,
    matchScore: 0.65 },
  { componentKey: "fast_stringer_hangers_lscz", label: "Simpson Strong-Tie LSCZ Adjustable Stringer Hangers w/ SD Connector Screws",
    quantityPerUnit: 0.6, supplier: "Niehaus",
    productName: "Simpson Strong-Tie SD9112 #9 x 1-1/2 in. Structural Connector Screws (100-Pack)", unitPrice: 0.15,
    priceUnit: "EA", extendedCost: 0.09,
    matchScore: 0.443 },
  { componentKey: "mat_ledger_board_2x10_pt", label: "2x10 #2 Pressure-Treated Pine Lumber (Ground Contact UC4A)",
    quantityPerUnit: 1.06, supplier: "HomeDepot",
    productName: "2 in. x 8 in. x 8 ft. #2 Ground Contact Pressure-Treated Southern Yellow Pine Lu", unitPrice: 1.69,
    priceUnit: "LF", extendedCost: 1.7914,
    matchScore: 0.735 },
  { componentKey: "fast_structural_ledger_screws", label: "1/2 in. x 5 in. Exterior Structural Ledger Screws (FastenMaster LedgerLOK / Simp",
    quantityPerUnit: 1.7, supplier: "HomeDepot",
    productName: "FastenMaster LedgerLOK 5 in. Flat-Head Ledger Screws (50-Pack)", unitPrice: 1.3,
    priceUnit: "EA", extendedCost: 2.21,
    matchScore: 0.562 },
  { componentKey: "mat_helical_pile_extension", label: "2-7/8 in. OD x 3.5 ft Galvanized Extension Shaft w/ Coupling Hardware",
    quantityPerUnit: 0.5, supplier: "JonesAndSons",
    productName: "Concrete Brick", unitPrice: 0.64,
    priceUnit: "EA", extendedCost: 0.32,
    matchScore: 0.419 },
  { componentKey: "mat_helical_pier_bracket_adjustable", label: "Adjustable 6x6 Post Base Steel Saddle Bracket w/ 3/4 in. Threaded Rod",
    quantityPerUnit: 1.0, supplier: "Menards",
    productName: "MiTek 6x6 Adjustable Post Base (G185)", unitPrice: 18.98,
    priceUnit: "EA", extendedCost: 18.98,
    matchScore: 0.433 },
  { componentKey: "mat_ridge_vent_baffled_4ft", label: "4 ft High-Impact Polypropylene Shingle-Over Ridge Vent w/ External Wind Baffle",
    quantityPerUnit: 1.05, supplier: "HomeDepot",
    productName: "Air Vent 4 ft. Plastic Shingle-Over Ridge Vent", unitPrice: 2.5,
    priceUnit: "LF", extendedCost: 2.625,
    matchScore: 0.671 },
  { componentKey: "mat_step_flashing_aluminum_cards", label: "Pre-Bent 0.019 in. Painted Aluminum Step Flashing Cards (7 in. x 4 in. x 4 in.)",
    quantityPerUnit: 2.64, supplier: "HomeDepot",
    productName: "Gibraltar 4 in. x 4 in. x 8 in. Aluminum Step Flashing (100-Pack)", unitPrice: 0.4,
    priceUnit: "EA", extendedCost: 1.056,
    matchScore: 0.545 },
  { componentKey: "fast_masonry_insulation_anchors", label: "3-1/2 in. Plastic-Washer Masonry Insulation Drive Anchors / Ramset Pins",
    quantityPerUnit: 0.172, supplier: "HomeDepot",
    productName: "Tapcon 1/4 in. x 2-3/4 in. Hex-Washer-Head Concrete Screws (75-Pack)", unitPrice: 0.31,
    priceUnit: "EA", extendedCost: 0.0533,
    matchScore: 0.425 },
  { componentKey: "mat_contractor_bags_tile", label: "Heavy-Duty 3-Mil 42-Gal Contractor Bags (Tile Allocation)",
    quantityPerUnit: 0.02, supplier: "Lowes",
    productName: "Steelcoat 42-Gallon 3-Mil Heavy-Duty Contractor Trash Bags (50-Count)", unitPrice: 0.66,
    priceUnit: "EA", extendedCost: 0.0132,
    matchScore: 0.63 },
  { componentKey: "mat_floor_runner_protection", label: "Heavy-Duty Corrugated Floor Protection (Ram Board / Cardboard)",
    quantityPerUnit: 0.1, supplier: "Menards",
    productName: "Ram Board Heavy-Duty Floor Protection (317 SF)", unitPrice: 0.19,
    priceUnit: "SF", extendedCost: 0.019,
    matchScore: 0.75 },
  { componentKey: "mat_aggregate_crushed_stone_ton", label: "Dense-Graded Crushed Limestone Aggregate (INDOT #53 / Dense Base)",
    quantityPerUnit: 1.95, supplier: "JonesAndSons",
    productName: "#73 Limestone", unitPrice: 24.95,
    priceUnit: "TON", extendedCost: 48.6525,
    matchScore: 0.588 },
  { componentKey: "mat_expansion_joint_material", label: "1/2 in. x 4 in. Asphaltic Impregnated Fiber Expansion Joint Strips",
    quantityPerUnit: 0.02, supplier: "Menards",
    productName: "Expansion Joint Fiber Strip 1/2 in. x 4 in. x 10 ft.", unitPrice: 0.4,
    priceUnit: "LF", extendedCost: 0.008,
    matchScore: 0.667 },
  { componentKey: "mat_rebar_no4_driveway_grid", label: "#4 Grade 60 Deformed Steel Rebar (1/2 in. Dia, 18 in. OC Each Way)",
    quantityPerUnit: 1.48, supplier: "HomeDepot",
    productName: "#4 x 10 ft. Grade 60 Rebar", unitPrice: 0.85,
    priceUnit: "LF", extendedCost: 1.258,
    matchScore: 0.77 },
  { componentKey: "mat_rebar_no4_stoop_cage", label: "#4 Grade 60 Rebar Reinforcement Cage & Foundation Tie Dowels",
    quantityPerUnit: 42.0, supplier: "Menards",
    productName: "#4 (1/2 in.) x 20 ft. Grade 60 Rebar", unitPrice: 0.65,
    priceUnit: "LF", extendedCost: 27.3,
    matchScore: 0.461 },
  { componentKey: "mat_cmu_blocks_8x8x16_hollow", label: "8 in. x 8 in. x 16 in. Lightweight / Normal Weight Hollow CMU Blocks (ASTM C90)",
    quantityPerUnit: 1.18, supplier: "Menards",
    productName: "8 in. x 8 in. x 16 in. Standard Hollow CMU Block", unitPrice: 2.28,
    priceUnit: "EA", extendedCost: 2.6904,
    matchScore: 0.48 },
  { componentKey: "mat_rebar_no4_cmu_reinforcing", label: "#4 Grade 60 Rebar (Verticals @ 32-48 in. OC & Horizontal Bond Beam)",
    quantityPerUnit: 0.65, supplier: "Menards",
    productName: "#4 (1/2 in.) x 20 ft. Grade 60 Rebar", unitPrice: 0.65,
    priceUnit: "LF", extendedCost: 0.4225,
    matchScore: 0.405 },
  { componentKey: "mat_joint_reinforcement_ladder_9ga", label: "9-Gauge Galvanized Ladder-Type Horizontal Wire Joint Reinforcement",
    quantityPerUnit: 0.75, supplier: "JonesAndSons",
    productName: "Rewall For 10\" Block", unitPrice: 0.5,
    priceUnit: "LF", extendedCost: 0.375,
    matchScore: 0.461 },
  { componentKey: "mat_brick_modular_clay_facing", label: "Standard Modular Facing Brick (ASTM C216 Grade SW, 3-5/8 x 2-1/4 x 7-5/8 in.)",
    quantityPerUnit: 7.35, supplier: "JonesAndSons",
    productName: "Concrete Brick", unitPrice: 0.64,
    priceUnit: "EA", extendedCost: 4.704,
    matchScore: 0.69 },
  { componentKey: "fast_brick_wall_ties_corrugated", label: "22-Gauge Corrugated Galvanized Steel Brick Ties & Hex Screws",
    quantityPerUnit: 0.42, supplier: "JonesAndSons",
    productName: "Heavy Duty Wall Tie", unitPrice: 0.16,
    priceUnit: "EA", extendedCost: 0.0672,
    matchScore: 0.42 },
  { componentKey: "mat_thru_wall_flashing_membrane", label: "40-Mil Self-Adhering Composite Base Thru-Wall Flashing Membrane",
    quantityPerUnit: 0.12, supplier: "JonesAndSons",
    productName: "12\" x 75' Self-Adhering Flashing Membrane", unitPrice: 0.91,
    priceUnit: "SF", extendedCost: 0.1092,
    matchScore: 0.486 },
  { componentKey: "mat_fence_posts_4x4x8_pt", label: "4x4x8 ft #2 Pressure-Treated Pine Fence Posts (Ground Contact UC4A)",
    quantityPerUnit: 0.138, supplier: "HomeDepot",
    productName: "2 in. x 4 in. x 8 ft. #2 Pressure-Treated Fence Rail", unitPrice: 0.75,
    priceUnit: "LF", extendedCost: 0.1035,
    matchScore: 0.709 },
  { componentKey: "mat_fence_rails_2x4x8_pt", label: "2x4x8 ft #2 Pressure-Treated Pine Horizontal Backer Rails",
    quantityPerUnit: 0.413, supplier: "HomeDepot",
    productName: "2 in. x 4 in. x 8 ft. #2 Pressure-Treated Fence Rail", unitPrice: 0.75,
    priceUnit: "LF", extendedCost: 0.3097,
    matchScore: 0.617 },
  { componentKey: "mat_fence_pickets_dogear_pt", label: "5/8 in. x 5-1/2 in. x 6 ft Pressure-Treated Pine Dog-Ear Pickets",
    quantityPerUnit: 2.28, supplier: "Lowes",
    productName: "Severe Weather 5/8-in x 5-1/2-in x 6-ft Treated Southern Yellow Pine Dog-Ear Fen", unitPrice: 2.18,
    priceUnit: "EA", extendedCost: 4.9704,
    matchScore: 0.76 },
  { componentKey: "fast_fence_nails_galvanized_ring", label: "1-7/8 in. x 0.099 in. Hot-Dipped Galvanized / Stainless Ring-Shank Coil Nails",
    quantityPerUnit: 14.5, supplier: "Menards",
    productName: "15-Degree Coil Siding Nails 1-7/8 in. Ring Shank (3,600 ct)", unitPrice: 0.01,
    priceUnit: "EA", extendedCost: 0.145,
    matchScore: 0.538 },
  { componentKey: "mat_top_rail_138_galv", label: "1-3/8 in. OD Swedged-End Galvanized Steel Top Rail (21 ft Length)",
    quantityPerUnit: 1.05, supplier: "Niehaus",
    productName: "ClarkDietrich 1-1/4 in. x 8 ft. Galvanized Metal Drywall Corner Bead", unitPrice: 0.31,
    priceUnit: "LF", extendedCost: 0.3255,
    matchScore: 0.406 },
];
export interface AssemblyMaterialCost { assemblyId: string; assemblyName: string;
  unitOfMeasure: string; pricedComponents: number; totalComponents: number;
  materialCostPerUnit: number; }
export const ASSEMBLY_MATERIAL_COSTS: readonly AssemblyMaterialCost[] = [
  { assemblyId: "demo-drywall-stud-bare", assemblyName: "Interior Drywall Demolition to Bare Studs",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 3, materialCostPerUnit: 0.03 },
  { assemblyId: "demo-flooring-carpet-pad", assemblyName: "Carpet, Rebond Pad, and Tack Strip Removal",
    unitOfMeasure: "SF", pricedComponents: 0,
    totalComponents: 2, materialCostPerUnit: 0 },
  { assemblyId: "demo-roofing-shingle-tearoff", assemblyName: "Asphalt Shingle Roof Tear-Off (1 Layer)",
    unitOfMeasure: "SQ", pricedComponents: 0,
    totalComponents: 2, materialCostPerUnit: 0 },
  { assemblyId: "demo-concrete-slab-4in", assemblyName: "Concrete Slab Demolition (4 in. Unreinforced)",
    unitOfMeasure: "SF", pricedComponents: 0,
    totalComponents: 2, materialCostPerUnit: 0 },
  { assemblyId: "conc-slab-4in-ongrade", assemblyName: "4 in. Concrete Slab-on-Grade (Unreinforced, 3500 PSI, Broom ",
    unitOfMeasure: "SF", pricedComponents: 1,
    totalComponents: 4, materialCostPerUnit: 0.52 },
  { assemblyId: "conc-footing-continuous-16x8", assemblyName: "Continuous Concrete Wall Footing (16 in. W x 8 in. D w/ 2 #4",
    unitOfMeasure: "LF", pricedComponents: 2,
    totalComponents: 4, materialCostPerUnit: 2.12 },
  { assemblyId: "conc-wall-cip-8in-8ft", assemblyName: "Cast-in-Place Concrete Foundation Wall (8 in. Thick x 8 ft H",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 5, materialCostPerUnit: 1.02 },
  { assemblyId: "conc-pier-sonotube-12x48", assemblyName: "Concrete Sonotube Pier (12 in. Dia x 48 in. Deep w/ Rebar & ",
    unitOfMeasure: "EA", pricedComponents: 5,
    totalComponents: 5, materialCostPerUnit: 27.36 },
  { assemblyId: "framing-wall-int-2x4-16oc", assemblyName: "2x4 Interior Non-Load Bearing Wall Framing (16 in. OC)",
    unitOfMeasure: "SF", pricedComponents: 0,
    totalComponents: 2, materialCostPerUnit: 0 },
  { assemblyId: "framing-wall-ext-2x6-16oc", assemblyName: "2x6 Exterior Load-Bearing Wall Framing (16 in. OC)",
    unitOfMeasure: "SF", pricedComponents: 1,
    totalComponents: 5, materialCostPerUnit: 0.03 },
  { assemblyId: "framing-floor-joist-2x10-16oc", assemblyName: "Floor Joist Framing System (2x10 Lumber, 16 in. OC)",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 2, materialCostPerUnit: 0.61 },
  { assemblyId: "framing-subfloor-osb-3-4", assemblyName: "Subfloor Sheathing (3/4 in. T&G OSB, Glued & Fastened)",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 2, materialCostPerUnit: 0.98 },
  { assemblyId: "framing-roof-rafter-2x8-16oc", assemblyName: "Roof Rafter Framing (2x8 Rafters, 16 in. OC, Up to 6:12 Pitc",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 3, materialCostPerUnit: 0.46 },
  { assemblyId: "deck-framing-pt-joist-beam", assemblyName: "Pressure-Treated Deck Framing System (16 in. OC, Posts, Beam",
    unitOfMeasure: "SF", pricedComponents: 3,
    totalComponents: 3, materialCostPerUnit: 1.43 },
  { assemblyId: "deck-surface-pt-5-4x6", assemblyName: "5/4x6 Pressure-Treated Decking Installation (Face-Screwed)",
    unitOfMeasure: "SF", pricedComponents: 1,
    totalComponents: 1, materialCostPerUnit: 1.9 },
  { assemblyId: "deck-surface-composite-grooved", assemblyName: "Composite Decking Installation (Capped Composite w/ Hidden F",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 2, materialCostPerUnit: 5.68 },
  { assemblyId: "deck-guardrail-wood-4in-baluster", assemblyName: "Wood Deck Guardrail System (4x4 Posts, 2x4 Rails, 2x2 Balust",
    unitOfMeasure: "LF", pricedComponents: 2,
    totalComponents: 4, materialCostPerUnit: 4.06 },
  { assemblyId: "roofing-shingles-arch-asphalt", assemblyName: "Architectural Asphalt Shingle Roofing Installation",
    unitOfMeasure: "SQ", pricedComponents: 2,
    totalComponents: 3, materialCostPerUnit: 386.23 },
  { assemblyId: "roofing-underlayment-synthetic", assemblyName: "Synthetic High-Performance Roof Underlayment",
    unitOfMeasure: "SQ", pricedComponents: 0,
    totalComponents: 1, materialCostPerUnit: 0 },
  { assemblyId: "roofing-icewater-shield-membrane", assemblyName: "Self-Adhering Ice & Water Shield Membrane (Modified Bitumen)",
    unitOfMeasure: "SQ", pricedComponents: 1,
    totalComponents: 1, materialCostPerUnit: 20.62 },
  { assemblyId: "roofing-flashing-drip-edge", assemblyName: "Aluminum Drip Edge Flashing Installation",
    unitOfMeasure: "LF", pricedComponents: 1,
    totalComponents: 1, materialCostPerUnit: 0.08 },
  { assemblyId: "siding-vinyl-lap-d4", assemblyName: "Vinyl Lap Siding Installation (Double 4 in. / 4.5 in. Profil",
    unitOfMeasure: "SQ", pricedComponents: 2,
    totalComponents: 3, materialCostPerUnit: 0.3 },
  { assemblyId: "siding-fibercement-lap-hardie", assemblyName: "Fiber Cement Lap Siding (James Hardie 8-1/4 in., 7 in. Expos",
    unitOfMeasure: "SQ", pricedComponents: 0,
    totalComponents: 3, materialCostPerUnit: 0 },
  { assemblyId: "moisture-barrier-wrb-housewrap", assemblyName: "Weather-Resistive Barrier (Housewrap / Tyvek) Taped",
    unitOfMeasure: "SQ", pricedComponents: 0,
    totalComponents: 2, materialCostPerUnit: 0 },
  { assemblyId: "insul-batt-fiberglass-r13-2x4", assemblyName: "Kraft-Faced Fiberglass Batt Insulation (R-13/R-15 in 2x4 Wal",
    unitOfMeasure: "SF", pricedComponents: 0,
    totalComponents: 1, materialCostPerUnit: 0 },
  { assemblyId: "insul-loosefill-attic-r38", assemblyName: "Blown-In Loose-Fill Attic Insulation (R-38 Fiberglass / Cell",
    unitOfMeasure: "SF", pricedComponents: 1,
    totalComponents: 4, materialCostPerUnit: 0.07 },
  { assemblyId: "door-interior-prehung-hc", assemblyName: "Prehung Interior Hollow-Core Door Installation",
    unitOfMeasure: "EA", pricedComponents: 2,
    totalComponents: 3, materialCostPerUnit: 148.98 },
  { assemblyId: "door-exterior-prehung-fiberglass", assemblyName: "Prehung Exterior Fiberglass Entry Door Installation",
    unitOfMeasure: "EA", pricedComponents: 0,
    totalComponents: 3, materialCostPerUnit: 0 },
  { assemblyId: "window-vinyl-retrofit-dh", assemblyName: "Vinyl Replacement Double-Hung Window Installation (Insert / ",
    unitOfMeasure: "EA", pricedComponents: 1,
    totalComponents: 3, materialCostPerUnit: 3.49 },
  { assemblyId: "drywall-wall-half-inch-l4", assemblyName: "1/2 in. Drywall on Walls (Hang, Tape & Level 4 Finish)",
    unitOfMeasure: "SF", pricedComponents: 3,
    totalComponents: 5, materialCostPerUnit: 0.59 },
  { assemblyId: "drywall-ceiling-half-inch-l4", assemblyName: "1/2 in. Sag-Resistant Drywall on Ceilings (Level 4 Finish)",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 4, materialCostPerUnit: 0.56 },
  { assemblyId: "drywall-typex-5-8-l4", assemblyName: "5/8 in. Type X Fire-Rated Drywall (Hang, Tape & Level 4 Fini",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 3, materialCostPerUnit: 0.67 },
  { assemblyId: "drywall-patch-repair-12x12", assemblyName: "Drywall Patch / Hole Repair (Up to 12 in. x 12 in.)",
    unitOfMeasure: "EA", pricedComponents: 2,
    totalComponents: 4, materialCostPerUnit: 0.31 },
  { assemblyId: "paint-wall-interior-latex-2coat", assemblyName: "Interior Wall Repainting (Surface Prep & 2 Coats Acrylic Lat",
    unitOfMeasure: "SF", pricedComponents: 3,
    totalComponents: 4, materialCostPerUnit: 0.25 },
  { assemblyId: "paint-drywall-new-primer-2coat", assemblyName: "Painting New Drywall (1 Coat PVA Primer & 2 Coats Acrylic La",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 4, materialCostPerUnit: 0.29 },
  { assemblyId: "paint-ceiling-interior-flat-2coat", assemblyName: "Interior Ceiling Painting (Surface Prep & 2 Coats Flat Latex",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 3, materialCostPerUnit: 0.13 },
  { assemblyId: "paint-trim-interior-enamel-2coat", assemblyName: "Interior Trim Painting (Baseboard / Casing, 2 Coats Acrylic ",
    unitOfMeasure: "LF", pricedComponents: 0,
    totalComponents: 3, materialCostPerUnit: 0 },
  { assemblyId: "flooring-lvp-clicklock-floating", assemblyName: "Luxury Vinyl Plank (LVP) Flooring (Click-Lock Floating, Atta",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 3, materialCostPerUnit: 3.57 },
  { assemblyId: "flooring-hardwood-solid-oak-3-4", assemblyName: "Solid 3/4 in. x 3-1/4 in. Oak Hardwood Flooring (Blind-Naile",
    unitOfMeasure: "SF", pricedComponents: 0,
    totalComponents: 2, materialCostPerUnit: 0 },
  { assemblyId: "flooring-carpet-pad-stretch", assemblyName: "Carpet & Rebond Pad Installation (Stretch-In, Power Stretche",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 4, materialCostPerUnit: 0.08 },
  { assemblyId: "tile-floor-porcelain-12x24", assemblyName: "Porcelain Floor Tile 12 in. x 24 in. (Polymer-Modified Thins",
    unitOfMeasure: "SF", pricedComponents: 3,
    totalComponents: 5, materialCostPerUnit: 3.23 },
  { assemblyId: "tile-underlayment-cement-board-half", assemblyName: "1/2 in. Cement Backer Board Underlayment (Thinset Bed & Tape",
    unitOfMeasure: "SF", pricedComponents: 3,
    totalComponents: 3, materialCostPerUnit: 1.75 },
  { assemblyId: "trim-baseboard-paintgrade-4in", assemblyName: "Paint-Grade Baseboard Installation (3-1/4 in. to 4-1/4 in. M",
    unitOfMeasure: "LF", pricedComponents: 1,
    totalComponents: 1, materialCostPerUnit: 1.58 },
  { assemblyId: "trim-casing-door-paintgrade", assemblyName: "Paint-Grade Door Casing Installation (2-1/4 in. to 3-1/2 in.",
    unitOfMeasure: "LF", pricedComponents: 1,
    totalComponents: 2, materialCostPerUnit: 0.94 },
  { assemblyId: "cabinet-base-kitchen-prehab", assemblyName: "Prefabricated Kitchen Base Cabinet Installation",
    unitOfMeasure: "EA", pricedComponents: 1,
    totalComponents: 2, materialCostPerUnit: 0.1 },
  { assemblyId: "plumb-toilet-replace-2pc-std", assemblyName: "Standard Two-Piece Toilet Replacement",
    unitOfMeasure: "EA", pricedComponents: 3,
    totalComponents: 4, materialCostPerUnit: 261.46 },
  { assemblyId: "plumb-faucet-kitchen-pulldown", assemblyName: "Single-Handle Kitchen Sink Pulldown Faucet Replacement",
    unitOfMeasure: "EA", pricedComponents: 1,
    totalComponents: 3, materialCostPerUnit: 119.0 },
  { assemblyId: "plumb-sink-kitchen-undermount", assemblyName: "Undermount / Drop-In Kitchen Sink Installation & Hookup",
    unitOfMeasure: "EA", pricedComponents: 2,
    totalComponents: 4, materialCostPerUnit: 143.98 },
  { assemblyId: "plumb-waterheater-electric-50gal", assemblyName: "50-Gallon Electric Tank Water Heater Replacement",
    unitOfMeasure: "EA", pricedComponents: 4,
    totalComponents: 6, materialCostPerUnit: 601.92 },
  { assemblyId: "hvac-minisplit-singlezone-12k", assemblyName: "Single-Zone Ductless Mini-Split Heat Pump Installation (12,0",
    unitOfMeasure: "EA", pricedComponents: 0,
    totalComponents: 6, materialCostPerUnit: 0 },
  { assemblyId: "hvac-furnace-gas-replacement", assemblyName: "Residential Gas Furnace Replacement (80%\\u201396% AFUE)",
    unitOfMeasure: "EA", pricedComponents: 2,
    totalComponents: 5, materialCostPerUnit: 7.76 },
  { assemblyId: "hvac-thermostat-smart-replace", assemblyName: "Digital Programmable / Smart Thermostat Replacement",
    unitOfMeasure: "EA", pricedComponents: 1,
    totalComponents: 1, materialCostPerUnit: 119.0 },
  { assemblyId: "elec-receptacle-duplex-tr-15a", assemblyName: "Standard Duplex Receptacle (15A/20A, Tamper-Resistant)",
    unitOfMeasure: "EA", pricedComponents: 3,
    totalComponents: 3, materialCostPerUnit: 3.57 },
  { assemblyId: "elec-switch-singlepole-15a", assemblyName: "Single-Pole Toggle / Decora Rocker Wall Switch",
    unitOfMeasure: "EA", pricedComponents: 1,
    totalComponents: 3, materialCostPerUnit: 0.06 },
  { assemblyId: "elec-lighting-wafer-led-6in", assemblyName: "Recessed LED Retrofit / Wafer Downlight (6 in. Canless Wafer",
    unitOfMeasure: "EA", pricedComponents: 2,
    totalComponents: 3, materialCostPerUnit: 12.56 },
  { assemblyId: "elec-circuit-dedicated-20a-50ft", assemblyName: "Dedicated 20A Branch Circuit Run (NM-B 12/2 up to 50 LF)",
    unitOfMeasure: "EA", pricedComponents: 3,
    totalComponents: 3, materialCostPerUnit: 41.08 },
  { assemblyId: "framing-floor-ijoist-19-2oc", assemblyName: "Engineered Wood I-Joist Floor Framing System (19.2 in. OC, R",
    unitOfMeasure: "SF", pricedComponents: 0,
    totalComponents: 4, materialCostPerUnit: 0 },
  { assemblyId: "framing-roof-truss-erection-24oc", assemblyName: "Pre-Engineered Wood Roof Truss Erection & Bracing (24 in. OC",
    unitOfMeasure: "SF", pricedComponents: 1,
    totalComponents: 3, materialCostPerUnit: 0.12 },
  { assemblyId: "sheathing-wall-osb-7-16", assemblyName: "Exterior Wall Sheathing (7/16 in. OSB, APA Rated, 8d Nails a",
    unitOfMeasure: "SF", pricedComponents: 1,
    totalComponents: 1, materialCostPerUnit: 0.49 },
  { assemblyId: "sheathing-roof-plywood-cdx-1-2", assemblyName: "Roof Deck Sheathing (1/2 in. CDX Plywood, APA Rated, Edge H-",
    unitOfMeasure: "SF", pricedComponents: 1,
    totalComponents: 2, materialCostPerUnit: 0.86 },
  { assemblyId: "framing-beam-lvl-2ply-1178", assemblyName: "Structural Engineered LVL Carrying Beam (2-Ply 1-3/4 in. x 1",
    unitOfMeasure: "LF", pricedComponents: 1,
    totalComponents: 1, materialCostPerUnit: 16.43 },
  { assemblyId: "deck-stairs-wood-stringer-step", assemblyName: "Exterior Wood Deck Stairs (Cut 2x12 PT Stringers & 5/4x6 Tre",
    unitOfMeasure: "EA", pricedComponents: 2,
    totalComponents: 2, materialCostPerUnit: 11.12 },
  { assemblyId: "deck-ledger-attachment-flashing", assemblyName: "Deck Ledger Board Attachment & Flashing (2x10 PT, Structural",
    unitOfMeasure: "LF", pricedComponents: 1,
    totalComponents: 4, materialCostPerUnit: 1.79 },
  { assemblyId: "found-pier-helical-steel", assemblyName: "Helical Pile Foundation Pier Alternative (Torque-Driven Stee",
    unitOfMeasure: "EA", pricedComponents: 2,
    totalComponents: 4, materialCostPerUnit: 19.3 },
  { assemblyId: "roofing-metal-standing-seam-24ga", assemblyName: "Standing Seam Metal Roofing (24ga Steel, 16 in. Snap-Lock/Me",
    unitOfMeasure: "SQ", pricedComponents: 0,
    totalComponents: 3, materialCostPerUnit: 0 },
  { assemblyId: "roofing-membrane-epdm-60mil", assemblyName: "EPDM Single-Ply Low-Slope Roof Membrane (60-Mil Non-Reinforc",
    unitOfMeasure: "SQ", pricedComponents: 0,
    totalComponents: 5, materialCostPerUnit: 0 },
  { assemblyId: "roofing-sbs-roll-selfadhered-cap", assemblyName: "Low-Slope SBS Modified Bitumen Roll Roofing (2-Ply Self-Adhe",
    unitOfMeasure: "SQ", pricedComponents: 0,
    totalComponents: 3, materialCostPerUnit: 0 },
  { assemblyId: "roofing-vent-ridge-shingleover", assemblyName: "Continuous Shingle-Over Ridge Vent Installation (External Ba",
    unitOfMeasure: "LF", pricedComponents: 1,
    totalComponents: 2, materialCostPerUnit: 2.62 },
  { assemblyId: "roofing-flashing-chimney-step-counter", assemblyName: "Chimney Step and Counter Flashing (Interlocking Step Metal &",
    unitOfMeasure: "LF", pricedComponents: 1,
    totalComponents: 3, materialCostPerUnit: 1.06 },
  { assemblyId: "roofing-flashing-pipe-boot", assemblyName: "Roof Plumbing Vent Pipe Boot Flashing (Elastomeric Collar Al",
    unitOfMeasure: "EA", pricedComponents: 0,
    totalComponents: 2, materialCostPerUnit: 0 },
  { assemblyId: "roofing-gutters-seamless-aluminum-5in", assemblyName: "5 in. Seamless Aluminum K-Style Gutter & Downspout Installat",
    unitOfMeasure: "LF", pricedComponents: 0,
    totalComponents: 5, materialCostPerUnit: 0 },
  { assemblyId: "insul-sprayfoam-closedcell-2in", assemblyName: "Closed-Cell Spray Polyurethane Foam Insulation (2 in. Thickn",
    unitOfMeasure: "SF", pricedComponents: 0,
    totalComponents: 3, materialCostPerUnit: 0 },
  { assemblyId: "insul-rigidfoam-xps-2in-foundation", assemblyName: "Extruded Polystyrene (XPS) Foundation Perimeter Insulation (",
    unitOfMeasure: "SF", pricedComponents: 0,
    totalComponents: 2, materialCostPerUnit: 0 },
  { assemblyId: "waterproofing-foundation-spray-bituminous", assemblyName: "Bituminous Foundation Spray Dampproofing / Waterproofing (Po",
    unitOfMeasure: "SF", pricedComponents: 0,
    totalComponents: 3, materialCostPerUnit: 0 },
  { assemblyId: "demo-roofing-shingle-tearoff-2layers", assemblyName: "Asphalt Shingle Roof Tear-Off (2 Layers)",
    unitOfMeasure: "SQ", pricedComponents: 0,
    totalComponents: 2, materialCostPerUnit: 0 },
  { assemblyId: "demo-flooring-tile-porcelain-thinset", assemblyName: "Ceramic / Porcelain Floor Tile Demolition (Scrape Thinset to",
    unitOfMeasure: "SF", pricedComponents: 1,
    totalComponents: 3, materialCostPerUnit: 0.01 },
  { assemblyId: "demo-cabinet-kitchen-base-wall", assemblyName: "Kitchen Cabinet Removal & Disposal (Base and Wall Cabinets)",
    unitOfMeasure: "LF", pricedComponents: 1,
    totalComponents: 2, materialCostPerUnit: 0.02 },
  { assemblyId: "demo-siding-exterior-lap", assemblyName: "Exterior Siding Demolition (Vinyl or Wood Lap Siding to Shea",
    unitOfMeasure: "SQ", pricedComponents: 0,
    totalComponents: 2, materialCostPerUnit: 0 },
  { assemblyId: "demo-deck-wood-framing-surface", assemblyName: "Exterior Wood Deck Demolition (Decking and Framing Removal)",
    unitOfMeasure: "SF", pricedComponents: 0,
    totalComponents: 2, materialCostPerUnit: 0 },
  { assemblyId: "earthwork-trench-excavation-mini", assemblyName: "Continuous Footing Trench Excavation via Mini-Excavator",
    unitOfMeasure: "CY", pricedComponents: 0,
    totalComponents: 1, materialCostPerUnit: 0 },
  { assemblyId: "subbase-aggregate-granular-compaction", assemblyName: "Granular Aggregate Fill Placement & Plate Compaction",
    unitOfMeasure: "CY", pricedComponents: 1,
    totalComponents: 2, materialCostPerUnit: 48.65 },
  { assemblyId: "conc-sidewalk-4in-formed-joints", assemblyName: "4 in. Concrete Sidewalk with Formwork & Expansion Joints",
    unitOfMeasure: "SF", pricedComponents: 1,
    totalComponents: 4, materialCostPerUnit: 0.01 },
  { assemblyId: "conc-driveway-6in-reinforced-4000psi", assemblyName: "6 in. Heavy-Duty Reinforced Concrete Driveway Slab (#4 Rebar",
    unitOfMeasure: "SF", pricedComponents: 1,
    totalComponents: 5, materialCostPerUnit: 1.26 },
  { assemblyId: "conc-stoop-steps-unit-cip", assemblyName: "Cast-in-Place Concrete Step & Stoop Unit (Form, Pour, Finish",
    unitOfMeasure: "EA", pricedComponents: 1,
    totalComponents: 4, materialCostPerUnit: 27.3 },
  { assemblyId: "masonry-cmu-stemwall-8in-reinforced", assemblyName: "8 in. Concrete Masonry Unit (CMU) Foundation Stem Wall (Rein",
    unitOfMeasure: "SF", pricedComponents: 3,
    totalComponents: 5, materialCostPerUnit: 3.49 },
  { assemblyId: "masonry-brick-veneer-residential", assemblyName: "Residential Brick Veneer Masonry (Ties, Mortar, Weep Holes &",
    unitOfMeasure: "SF", pricedComponents: 2,
    totalComponents: 4, materialCostPerUnit: 4.81 },
  { assemblyId: "fence-wood-privacy-6ft-pt", assemblyName: "6 ft Wood Privacy Fence Installation (PT Pine, 4x4 Posts in ",
    unitOfMeasure: "LF", pricedComponents: 3,
    totalComponents: 4, materialCostPerUnit: 5.38 },
  { assemblyId: "fence-chainlink-galvanized-4ft", assemblyName: "4 ft Galvanized Chain Link Fence Installation (Terminal/Line",
    unitOfMeasure: "LF", pricedComponents: 1,
    totalComponents: 6, materialCostPerUnit: 0.33 },
];
/** Precomputed material-cost rollup for an assembly ID, or undefined. */
export function assemblyMaterialCost(id: string): AssemblyMaterialCost | undefined {
  return ASSEMBLY_MATERIAL_COSTS.find((a) => a.assemblyId === id); }
