/** TradeOS Assembly Library — source registry (58 sources). */
export interface TradeosAssemblySource { sourceId: string; sourceName: string; sourceOrganization: string; sourceDocumentTitle: string; sourceUrl: string; }

export const TRADEOS_ASSEMBLY_SOURCES: readonly TradeosAssemblySource[] = [
  { sourceId: "SRC-0001", sourceName: "OSHA Fall Protection in Residential Construction",
    sourceOrganization: "Occupational Safety and Health Administration (OSHA)",
    sourceDocumentTitle: "29 CFR 1926.501(b)(10) Roofing Operations on Low-Slope and Steep Roofs", sourceUrl: "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.501" },
  { sourceId: "SRC-0002", sourceName: "ARMA Residential Asphalt Roofing Manual",
    sourceOrganization: "Asphalt Roofing Manufacturers Association (ARMA)",
    sourceDocumentTitle: "Residential Asphalt Roofing Manual - Design and Application Methods", sourceUrl: "https://www.asphaltroofing.org/" },
  { sourceId: "SRC-0003", sourceName: "EPA Construction and Demolition Debris Generation Guide",
    sourceOrganization: "U.S. Environmental Protection Agency (EPA)",
    sourceDocumentTitle: "Advancing Sustainable Materials Management: Fact Sheet on C&D Debris", sourceUrl: "https://www.epa.gov/" },
  { sourceId: "SRC-0004", sourceName: "ACI 318 Building Code Requirements for Structural Concrete",
    sourceOrganization: "American Concrete Institute (ACI)",
    sourceDocumentTitle: "ACI 318-19: Building Code Requirements for Structural Concrete and Commentary", sourceUrl: "https://www.concrete.org/" },
  { sourceId: "SRC-0005", sourceName: "ACI 332 Residential Code Requirements for Structural Concrete",
    sourceOrganization: "American Concrete Institute (ACI)",
    sourceDocumentTitle: "ACI 332-20: Residential Code Requirements for Structural Concrete", sourceUrl: "https://www.concrete.org/" },
  { sourceId: "SRC-0006", sourceName: "2021 International Residential Code (IRC) Foundation Standards",
    sourceOrganization: "International Code Council (ICC)",
    sourceDocumentTitle: "2021 International Residential Code: Chapter 4 Foundations (Sections R403, R404)", sourceUrl: "https://codes.iccsafe.org/content/IRC2021P1/chapter-4-foundations" },
  { sourceId: "SRC-0007", sourceName: "ASTM E1643 Water Vapor Retarders Under Concrete Slabs",
    sourceOrganization: "ASTM International",
    sourceDocumentTitle: "ASTM E1643: Standard Practice for Selection, Design, Installation, and Inspection of Water Vapor Retarders", sourceUrl: "https://www.astm.org/e1643-18a.html" },
  { sourceId: "SRC-0008", sourceName: "2021 IRC Chapter 6 Wall Construction",
    sourceOrganization: "International Code Council (ICC)",
    sourceDocumentTitle: "2021 International Residential Code: Chapter 6 Wall Construction (Table R602.3(1) and Table R602.3(5))", sourceUrl: "https://codes.iccsafe.org/content/IRC2021P1/chapter-6-wall-construction" },
  { sourceId: "SRC-0009", sourceName: "American Wood Council DCA 6 Prescriptive Residential Wood Deck Construction Guide",
    sourceOrganization: "American Wood Council (AWC)",
    sourceDocumentTitle: "Design for Code Acceptance (DCA 6): Prescriptive Residential Wood Deck Construction Guide", sourceUrl: "https://awc.org/wp-content/uploads/2022/03/AWC-DCA62015-DeckGuide-1804.pdf" },
  { sourceId: "SRC-0010", sourceName: "APA Engineered Wood Association Subfloor Specification",
    sourceOrganization: "APA - The Engineered Wood Association",
    sourceDocumentTitle: "Engineered Wood Construction Guide: Form E30 (Flooring and Subflooring Systems)", sourceUrl: "https://www.apawood.org/" },
  { sourceId: "SRC-0011", sourceName: "Trex Composite Decking Installation Guide",
    sourceOrganization: "Trex Company, Inc.",
    sourceDocumentTitle: "Trex Decking & Railing Installation Guide", sourceUrl: "https://www.trex.com/" },
  { sourceId: "SRC-0012", sourceName: "GAF Timberline HDZ Architectural Shingles Technical Data Sheet",
    sourceOrganization: "GAF Roofing",
    sourceDocumentTitle: "GAF Timberline HDZ Shingles Application Instructions & Architectural Data", sourceUrl: "https://www.gaf.com/" },
  { sourceId: "SRC-0013", sourceName: "CertainTeed DiamondDeck Synthetic Underlayment Specification",
    sourceOrganization: "CertainTeed Corporation",
    sourceDocumentTitle: "DiamondDeck High Performance Synthetic Roofing Underlayment Technical Data", sourceUrl: "https://www.certainteed.com/" },
  { sourceId: "SRC-0014", sourceName: "Grace Ice & Water Shield Technical Bulletin",
    sourceOrganization: "GCP Applied Technologies",
    sourceDocumentTitle: "GCP Grace Ice & Water Shield Self-Adhered Roofing Underlayment Data Sheet", sourceUrl: "https://gcpat.com/" },
  { sourceId: "SRC-0015", sourceName: "Vinyl Siding Institute (VSI) Installation Manual",
    sourceOrganization: "Vinyl Siding Institute",
    sourceDocumentTitle: "Vinyl Siding, Soffit and Fascia Installation Manual", sourceUrl: "https://www.vinylsiding.org/" },
  { sourceId: "SRC-0016", sourceName: "James Hardie HardiePlank Lap Siding Installation Guide",
    sourceOrganization: "James Hardie Building Products Inc.",
    sourceDocumentTitle: "HardiePlank HZ5 Lap Siding Product Instructions & Code Compliance", sourceUrl: "https://www.jameshardie.com/" },
  { sourceId: "SRC-0017", sourceName: "DuPont Tyvek HomeWrap Installation Guidelines",
    sourceOrganization: "DuPont Performance Building Solutions",
    sourceDocumentTitle: "DuPont Tyvek Water-Resistive Barriers Installation Guidelines", sourceUrl: "https://www.dupont.com/building/tyvek-homewrap.html" },
  { sourceId: "SRC-0018", sourceName: "Gypsum Association GA-216 Application & Finishing of Gypsum Panel Products",
    sourceOrganization: "Gypsum Association",
    sourceDocumentTitle: "GA-216-2021: Application and Finishing of Gypsum Panel Products", sourceUrl: "https://gypsum.org/" },
  { sourceId: "SRC-0019", sourceName: "Gypsum Association GA-214 Recommended Levels of Gypsum Board Finish",
    sourceOrganization: "Gypsum Association",
    sourceDocumentTitle: "GA-214-2020: Recommended Levels of Finish for Gypsum Board, Glass Mat and Paper-Faced Panels", sourceUrl: "https://gypsum.org/" },
  { sourceId: "SRC-0020", sourceName: "USG Sheetrock Brand Gypsum Construction Handbook",
    sourceOrganization: "United States Gypsum Company (USG)",
    sourceDocumentTitle: "The Gypsum Construction Handbook (7th Edition)", sourceUrl: "https://www.usg.com/" },
  { sourceId: "SRC-0021", sourceName: "Painting Contractors Association (PCA) Standards P1 and P14",
    sourceOrganization: "Painting Contractors Association (PCA)",
    sourceDocumentTitle: "PCA Standard P1: Touch-Up Painting & Standard P14: Quality Specifications for Interior Painting", sourceUrl: "https://pcapainted.org/standards/" },
  { sourceId: "SRC-0022", sourceName: "Sherwin-Williams ProMar 200 / PVA Primer Technical Bulletins",
    sourceOrganization: "The Sherwin-Williams Company",
    sourceDocumentTitle: "ProMar 200 Zero VOC Latex & PVA Drywall Primer Technical Data Sheets", sourceUrl: "https://www.sherwin-williams.com/" },
  { sourceId: "SRC-0023", sourceName: "National Wood Flooring Association (NWFA) Installation Guidelines",
    sourceOrganization: "National Wood Flooring Association (NWFA)",
    sourceDocumentTitle: "NWFA Wood Flooring Installation Guidelines (Publication No. A100)", sourceUrl: "https://www.nwfa.org/" },
  { sourceId: "SRC-0024", sourceName: "Tile Council of North America (TCNA) Handbook for Ceramic, Glass, and Stone Tile Installation",
    sourceOrganization: "Tile Council of North America (TCNA)",
    sourceDocumentTitle: "2023 TCNA Handbook: Method F144 (Cement Backer Board over Plywood Subfloor)", sourceUrl: "https://www.tcnatile.com/" },
  { sourceId: "SRC-0025", sourceName: "Carpet and Rug Institute (CRI) 105 Residential Installation Standard",
    sourceOrganization: "The Carpet and Rug Institute (CRI)",
    sourceDocumentTitle: "CRI 105: Standard for Installation of Residential Carpet", sourceUrl: "https://carpet-rug.org/" },
  { sourceId: "SRC-0026", sourceName: "Shaw Floors Luxury Vinyl Plank Installation Guide",
    sourceOrganization: "Shaw Industries Group, Inc.",
    sourceDocumentTitle: "Shaw Floort\u00e9 Resilient Click / Floating Luxury Vinyl Plank Installation Manual", sourceUrl: "https://shawfloors.com/" },
  { sourceId: "SRC-0027", sourceName: "Owens Corning EcoTouch Fiberglass Batt Insulation Technical Data",
    sourceOrganization: "Owens Corning",
    sourceDocumentTitle: "EcoTouch PINK FIBERGLAS Thermal Batt Insulation Product Guide", sourceUrl: "https://www.owenscorning.com/" },
  { sourceId: "SRC-0028", sourceName: "Therma-Tru Exterior Entry Door System Installation Manual",
    sourceOrganization: "Therma-Tru Doors",
    sourceDocumentTitle: "Therma-Tru Fiberglass and Steel Exterior Door Systems Installation Instructions", sourceUrl: "https://www.thermatru.com/" },
  { sourceId: "SRC-0029", sourceName: "Andersen Replacement Windows Installation Guide",
    sourceOrganization: "Andersen Windows & Doors",
    sourceDocumentTitle: "Insert Replacement Double-Hung Windows Installation Guide", sourceUrl: "https://www.andersenwindows.com/" },
  { sourceId: "SRC-0030", sourceName: "Kohler Two-Piece Water Closet Installation Manual",
    sourceOrganization: "Kohler Co.",
    sourceDocumentTitle: "KOHLER Tresham Two-Piece Elongated Toilet Installation Manual", sourceUrl: "https://manuals.plus/asin/B00L4C2M40" },
  { sourceId: "SRC-0031", sourceName: "Oatey Toilet Flange & Wax Bowl Ring Guide",
    sourceOrganization: "Oatey Co.",
    sourceDocumentTitle: "How to Install a Toilet Flange and Wax Bowl Ring Project Guide", sourceUrl: "https://www.oatey.com/resources/project-guides/install-toilet-flange" },
  { sourceId: "SRC-0032", sourceName: "Moen Single-Handle Pulldown Kitchen Faucet Instruction Sheet",
    sourceOrganization: "Moen Incorporated",
    sourceDocumentTitle: "Single Handle Pulldown Kitchen Faucet Installation Instructions INS10294A", sourceUrl: "https://assets.moen.com/shared/docs/instruction-sheets/ins10294a.pdf" },
  { sourceId: "SRC-0033", sourceName: "Rheem Performance Platinum Electric Water Heater Specification",
    sourceOrganization: "Rheem Manufacturing Company",
    sourceDocumentTitle: "Performance Platinum Electric Storage Water Heater Use & Care Manual", sourceUrl: "https://manuals.plus/m/e86eb01291b80e9cc047dc4900fd04a97c694540e874b2b5f1bc5f3fe4d8d8e1" },
  { sourceId: "SRC-0034", sourceName: "Leviton Tamper-Resistant Wiring Devices Specification",
    sourceOrganization: "Leviton Manufacturing Co., Inc.",
    sourceDocumentTitle: "Leviton Decora Plus Tamper-Resistant Receptacles & Commercial Switches", sourceUrl: "https://leviton.com/products/tdr15-e" },
  { sourceId: "SRC-0035", sourceName: "Cooper Lighting HALO HLB6 Slim Canless LED Downlight Spec Sheet",
    sourceOrganization: "Cooper Lighting Solutions",
    sourceDocumentTitle: "HALO HLB 6-inch Round Canless LED Downlights Specification Sheet", sourceUrl: "https://www.cooperlighting.com/api/assets/v1/file/CLS/content/3c2d17327ab346528e24ad41007dd610/HALO-HLB-6-inch-Round-0-10V-Canless-LED-Downlights-spec-sheet.pdf" },
  { sourceId: "SRC-0036", sourceName: "NFPA 70 National Electrical Code (NEC)",
    sourceOrganization: "National Fire Protection Association (NFPA)",
    sourceDocumentTitle: "NFPA 70: National Electrical Code (2020/2023 Edition)", sourceUrl: "https://www.nfpa.org/codes-and-standards/all-codes-and-standards/list-of-codes-and-standards/detail?code=70" },
  { sourceId: "SRC-0037", sourceName: "Mitsubishi Electric M-Series Mini-Split Installation Manual",
    sourceOrganization: "Mitsubishi Electric Trane HVAC US",
    sourceDocumentTitle: "M-Series MSZ-FS Wall-Mounted Indoor Unit and MUZ-FS Outdoor Heat Pump Installation Manual", sourceUrl: "https://www.mitsubishicomfort.com/" },
  { sourceId: "SRC-0038", sourceName: "Carrier Infinity 96 Gas Furnace Product Data",
    sourceOrganization: "Carrier Corporation",
    sourceDocumentTitle: "Carrier 59MN7 Condensing Gas Furnace Installation Instructions", sourceUrl: "https://www.carrier.com/" },
  { sourceId: "SRC-0039", sourceName: "Google Nest Learning Thermostat Installation Guide",
    sourceOrganization: "Google LLC",
    sourceDocumentTitle: "Nest Learning Thermostat Professional Installation and Wiring Guide", sourceUrl: "https://support.google.com/googlenest/" },
  { sourceId: "SRC-0040", sourceName: "SharkBite Plumbing Solutions Catalog",
    sourceOrganization: "Reliance Worldwide Corporation (RWC)",
    sourceDocumentTitle: "SharkBite Push-to-Connect Plumbing Solutions Product Catalog", sourceUrl: "https://www.sharkbite.com/sites/default/files/files/SB-US-Product-Catalog-2024-v2.pdf" },
  { sourceId: "SRC-0051", sourceName: "Weyerhaeuser Trus Joist TJI Specifier's Guide & APA PRI-400",
    sourceOrganization: "Weyerhaeuser / APA - The Engineered Wood Association",
    sourceDocumentTitle: "Trus Joist TJI Joist Specifier's Guide (TJ-4000) & APA PRI-400 Performance Rated I-Joists", sourceUrl: "https://www.weyerhaeuser.com/woodproducts/engineered-lumber/trus-joist-tji-joists/" },
  { sourceId: "SRC-0052", sourceName: "TPI 1 / WTCA Building Component Safety Information (BCSI)",
    sourceOrganization: "Truss Plate Institute (TPI) & Structural Building Components Association (SBCA)",
    sourceDocumentTitle: "BCSI-B1: Guide for Handling, Installing, Restraining & Bracing Metal Plate Connected Wood Trusses", sourceUrl: "https://www.sbcindustry.com/bcsi" },
  { sourceId: "SRC-0053", sourceName: "APA Form Q300 Wall Sheathing & 2021 IRC Table R602.3(1)/(3)",
    sourceOrganization: "APA - The Engineered Wood Association / International Code Council",
    sourceDocumentTitle: "APA Form Q300: Wall Sheathing & 2021 International Residential Code (IRC) Table R602.3(1) Fastener Schedule", sourceUrl: "https://www.apawood.org/publication-search?q=Q300" },
  { sourceId: "SRC-0054", sourceName: "APA Form E30 Roof Construction Guide & 2021 IRC Table R803.1",
    sourceOrganization: "APA - The Engineered Wood Association",
    sourceDocumentTitle: "Engineered Wood Construction Guide: Roof Sheathing (Form E30)", sourceUrl: "https://www.apawood.org/roof-sheathing" },
  { sourceId: "SRC-0055", sourceName: "APA Product Report PR-L501 & Weyerhaeuser Microllam LVL User's Guide",
    sourceOrganization: "APA - The Engineered Wood Association / Weyerhaeuser",
    sourceDocumentTitle: "APA PR-L501 Performance-Rated Laminated Veneer Lumber & Microllam LVL 2.0E Technical Guide", sourceUrl: "https://www.weyerhaeuser.com/woodproducts/engineered-lumber/microllam-lvl-beams/" },
  { sourceId: "SRC-0056", sourceName: "2021 IRC Section R311.7 Stairways & AWC DCA 6 Deck Stair Detail",
    sourceOrganization: "International Code Council / American Wood Council",
    sourceDocumentTitle: "2021 International Residential Code Section R311.7 Stairways & AWC DCA 6 Prescriptive Residential Deck Guide (Stair Geometry)", sourceUrl: "https://awc.org/wp-content/uploads/2022/03/AWC-DCA62015-DeckGuide-1804.pdf" },
  { sourceId: "SRC-0057", sourceName: "2021 IRC Section R507.9 & FastenMaster LedgerLOK Evaluation Report ESR-1078",
    sourceOrganization: "International Code Council Evaluation Service (ICC-ES)",
    sourceDocumentTitle: "ICC-ES ESR-1078: FastenMaster LedgerLOK Structural Wood Screw & 2021 IRC R507.9 Deck Ledger Connection", sourceUrl: "https://icc-es.org/report-listing/esr-1078/" },
  { sourceId: "SRC-0058", sourceName: "ICC-ES AC358 Acceptance Criteria for Helical Foundation Systems & Chance Technical Manual",
    sourceOrganization: "ICC-ES / Hubbell Power Systems (Chance Civil Construction)",
    sourceDocumentTitle: "ICC-ES AC358: Acceptance Criteria for Helical Pile Foundation Systems & Chance Technical Design Manual", sourceUrl: "https://www.hubbell.com/chancefoundationsolutions/en" },
  { sourceId: "SRC-0059", sourceName: "Metal Construction Association (MCA) Metal Roof Residential Technical Guide",
    sourceOrganization: "Metal Construction Association (MCA) / SMACNA",
    sourceDocumentTitle: "Metal Roof Residential Guide & SMACNA Architectural Sheet Metal Manual (7th Edition, Ch. 7 Standing Seam)", sourceUrl: "https://metalconstruction.org/" },
  { sourceId: "SRC-0060", sourceName: "Carlisle SynTec Systems Sure-Seal EPDM Design & Installation Guide",
    sourceOrganization: "Carlisle SynTec Systems",
    sourceDocumentTitle: "Sure-Seal Non-Reinforced EPDM Roofing Systems Specification Manual & NRCA Low-Slope Membrane Manual", sourceUrl: "https://www.carlislesyntec.com/" },
  { sourceId: "SRC-0061", sourceName: "CertainTeed Flintlastic SA Self-Adhering SBS Modified Bitumen Roof Manual",
    sourceOrganization: "CertainTeed Corporation",
    sourceDocumentTitle: "Flintlastic SA Self-Adhering SBS Modified Bitumen Roofing Systems Manual & ASTM D6164", sourceUrl: "https://www.certainteed.com/commercial-roofing/products/flintlastic-sa-cap/" },
  { sourceId: "SRC-0062", sourceName: "Air Vent Inc. Principles of Attic Ventilation & ShingleVent II Guide",
    sourceOrganization: "Air Vent Inc. (Gibraltar Industries) / 2021 IRC Section R806",
    sourceDocumentTitle: "Principles of Attic Ventilation & ShingleVent II Shingle-Over Ridge Vent Installation Instructions", sourceUrl: "https://www.airvent.com/" },
  { sourceId: "SRC-0063", sourceName: "NRCA Roofing Manual: Architectural Metal Flashing & 2021 IRC R905.2.8.1",
    sourceOrganization: "National Roofing Contractors Association (NRCA)",
    sourceDocumentTitle: "The NRCA Roofing Manual: Architectural Metal Flashing and Moisture Control (Masonry Chimney Flashing)", sourceUrl: "https://www.nrca.net/" },
  { sourceId: "SRC-0064", sourceName: "Oatey Master Flash & Roof Flashing Installation Guide / 2021 IPC P3103.1",
    sourceOrganization: "Oatey Co. / International Code Council",
    sourceDocumentTitle: "Oatey All-Flash / Master Flash Roof Flashing Technical Specification & 2021 IPC Section P3103.1", sourceUrl: "https://www.oatey.com/products/oatey-allflash-no-calk-roof-flashings" },
  { sourceId: "SRC-0065", sourceName: "SMACNA Architectural Sheet Metal Manual: Gutters & Downspouts",
    sourceOrganization: "Sheet Metal and Air Conditioning Contractors' National Association (SMACNA)",
    sourceDocumentTitle: "SMACNA Architectural Sheet Metal Manual (7th Edition, Chapter 1: Gutters and Downspouts)", sourceUrl: "https://www.smacna.org/" },
  { sourceId: "SRC-0066", sourceName: "SPFA-143 / Huntsman Heatlok HFO Technical Data Sheet",
    sourceOrganization: "Spray Polyurethane Foam Alliance (SPFA) / Huntsman Building Solutions",
    sourceDocumentTitle: "SPFA-143 Guidelines for Closed-Cell SPF & Heatlok HFO Closed-Cell Insulation Technical Manual", sourceUrl: "https://huntsmanbuildingsolutions.com/en-US/products/insulation/spray-foam/heatlok-hfo" },
  { sourceId: "SRC-0067", sourceName: "Owens Corning FOAMULAR & FOAMULAR NGX XPS Technical Bulletin / ASTM C578",
    sourceOrganization: "Owens Corning / ASTM International",
    sourceDocumentTitle: "FOAMULAR NGX Extruded Polystyrene (XPS) Technical Data Sheet & ASTM C578 Type IV Standard", sourceUrl: "https://www.owenscorning.com/en-us/insulation/products/foamular-ngx-250" },
  { sourceId: "SRC-0068", sourceName: "2021 IRC Section R406 & Tremco Residential Foundation Coatings Specification",
    sourceOrganization: "International Code Council / Tremco Commercial Sealants & Waterproofing",
    sourceDocumentTitle: "2021 IRC Section R406 Foundation Waterproofing and Dampproofing & Tremco Barrier Solutions Specification", sourceUrl: "https://codes.iccsafe.org/content/IRC2021P1/chapter-4-foundations" },
];

/** Assembly source record by exact source ID, or undefined when the ID is not in the registry. */
export function getTradeosAssemblySource(sourceId: string): TradeosAssemblySource | undefined {
  return TRADEOS_ASSEMBLY_SOURCES.find((s) => s.sourceId === sourceId);
}
