import { Router } from "express";
import { costbookController as ctrl } from "../controllers/costbook.controller";
import { asyncHandler } from "../middleware/asyncHandler";

export const costbookRouter = Router();

costbookRouter.get("/workspace", asyncHandler(ctrl.workspace));
costbookRouter.get("/labor-rates", asyncHandler(ctrl.listLaborRates));
costbookRouter.get("/labor-rates/:id", asyncHandler(ctrl.getLaborRate));
costbookRouter.post("/labor-rates", asyncHandler(ctrl.createLaborRate));
costbookRouter.patch("/labor-rates/:id", asyncHandler(ctrl.updateLaborRate));
costbookRouter.delete("/labor-rates/:id", asyncHandler(ctrl.removeLaborRate));
costbookRouter.get("/materials", asyncHandler(ctrl.listMaterials));
costbookRouter.get("/materials/:id", asyncHandler(ctrl.getMaterial));
costbookRouter.post("/materials", asyncHandler(ctrl.createMaterial));
costbookRouter.patch("/materials/:id", asyncHandler(ctrl.updateMaterial));
costbookRouter.get("/divisions", asyncHandler(ctrl.listDivisions));
costbookRouter.get("/divisions/:id", asyncHandler(ctrl.getDivision));
costbookRouter.post("/divisions", asyncHandler(ctrl.createDivision));
costbookRouter.patch("/divisions/:id", asyncHandler(ctrl.updateDivision));
costbookRouter.delete("/divisions/:id", asyncHandler(ctrl.removeDivision));
costbookRouter.get("/categories", asyncHandler(ctrl.listCategories));
costbookRouter.get("/categories/:id", asyncHandler(ctrl.getCategory));
costbookRouter.post("/categories", asyncHandler(ctrl.createCategory));
costbookRouter.patch("/categories/:id", asyncHandler(ctrl.updateCategory));
costbookRouter.delete("/categories/:id", asyncHandler(ctrl.removeCategory));
costbookRouter.get("/subcategories", asyncHandler(ctrl.listSubcategories));
costbookRouter.get("/subcategories/:id", asyncHandler(ctrl.getSubcategory));
costbookRouter.post("/subcategories", asyncHandler(ctrl.createSubcategory));
costbookRouter.patch("/subcategories/:id", asyncHandler(ctrl.updateSubcategory));
costbookRouter.delete("/subcategories/:id", asyncHandler(ctrl.removeSubcategory));
